import '../../features/shop/models/category_model.dart';
import '../../features/shop/models/product_model.dart';
import '../../features/shop/models/products_attributes_model.dart';
import '../../features/shop/models/products_variations_model.dart';

final List<CategoryModel> categoriesDummyData = [
  CategoryModel(
    id: 'cakes',
    name: {
      'ar': 'الكيكات',
      'en': 'Cakes',
    },
    image: 'assets/images/catgorey_images/Cakes.jpg',
    description: {
      'ar': 'استمتع بتشكيلة واسعة من الكيكات الطازجة.',
      'en': 'Enjoy a wide range of delicious cakes.',
    },
    isFeatured: false,
  ),
  CategoryModel(
    id: 'oriental',
    name: {
      'ar': 'الحلويات الشرقية',
      'en': 'Oriental Desserts',
    },
    image: 'assets/images/catgorey_images/OrientalDesserts.jpg',
    description: {
      'ar': 'اكتشف مذاق الحلويات الشرقية الأصيلة.',
      'en': 'Discover the timeless beauty of Oriental desserts.',
    },
    isFeatured: false,
  ),
  CategoryModel(
    id: 'western',
    name: {
      'ar': 'الحلويات الغربية',
      'en': 'Western Desserts',
    },
    image: 'assets/images/catgorey_images/WesternDesserts.jpg',
    description: {
      'ar': 'تذوق أفضل الحلويات الغربية.',
      'en': 'Enjoy the best Western desserts.',
    },
    isFeatured: false,
  ),
  CategoryModel(
    id: 'donuts',
    name: {
      'ar': 'دوناتس',
      'en': 'Donuts',
    },
    image: 'assets/images/catgorey_images/Donuts.jpg',
    description: {
      'ar': 'دوناتس طازجة ولذيذة!',
      'en': 'Delicious donuts!',
    },
    isFeatured: false,
  ),
  CategoryModel(
    id: 'cookies',
    name: {
      'ar': 'بسكويت',
      'en': 'Cookies',
    },
    image: 'assets/images/catgorey_images/Biscuits&Cookies.jpg',
    description: {
      'ar': 'بسكويت وكوكيز مقرمشة ولذيذة.',
      'en': 'Biscuits and cookies are crispy and delicious.',
    },
    isFeatured: false,
  ),
  CategoryModel(
    id: 'healthy',
    name: {
      'ar': 'الحلويات الصحية',
      'en': 'Healthy Desserts',
    },
    image: 'assets/images/catgorey_images/HealthyDesserts.jpg',
    description: {
      'ar': 'حلويات لذيذة وصحية!',
      'en': 'Delicious and healthy desserts!',
    },
    isFeatured: false,
  )
];
/* 
List<ProductModel> initializeDummyData() {
  return [
    // Cake ProductModels
    ProductModel(
      stock: 2,
      id: 'cake_001',
      name: 'الكيكة الفانيليا الكلاسيكية',
      description: 'كيكة فانيليا طرية وناعمة، مغطاة بكريمة زبدة لذيذة وخفيفة.',
      price: 25.00,
      productType: 'ProductType.size',
      thumbnail: 'assets/images/products/cakes/vanilla_cake.jpg',
      salePrice: 20.00,
      category: 'cakes',
      imageUrl: 'assets/images/products/cakes/vanilla_cake.jpg',
      tags: ['كيكات', 'فانيليا', 'صحي'],
      productAttributes: ProductAttributeModel(
        name: 'Size',
        values: ['Large', 'Medium', 'Small'],
      ),
      productVariations: [
        ProductVariationModel(
          id: '1',
          stock: 2,
          price: 10,
          salePrice: 8,
          attributeValues: {'Size': 'Small'},
        ),
        ProductVariationModel(
          id: '2',
          stock: 2,
          price: 10,
          salePrice: 8,
          attributeValues: {'Size': 'Medium'},
        ),
        ProductVariationModel(
          id: '3',
          stock: 2,
          price: 10,
          salePrice: 8,
          attributeValues: {'Size': 'Large'},
        ),
      ],
    ),
    ProductModel(
      stock: 2,
      id: 'cake_002',
      name: 'كيكة الشوكولاتة الكلاسيكية',
      description: 'كيكة شوكولاتة غنية وطرية، مغطاة بصوص الشوكولاتة الساخن.',
      price: 30.00,
      productType: 'ProductType.size',
      thumbnail: 'assets/images/products/cakes/chocolate_cake.jpg',
      salePrice: 20.00,
      category: 'cakes',
      imageUrl: 'assets/images/products/cakes/chocolate_cake.jpg',
      tags: ['كيكات', 'شوكولاتة', 'صحي'],
      productAttributes: ProductAttributeModel(
        name: 'Size',
        values: ['Large', 'Medium', 'Small'],
      ),
      productVariations: [
        ProductVariationModel(
          id: '1',
          stock: 2,
          price: 10,
          salePrice: 8,
          attributeValues: {'Size': 'Small'},
        ),
        ProductVariationModel(
          id: '2',
          stock: 2,
          price: 15,
          salePrice: 10,
          attributeValues: {'Size': 'Medium'},
        ),
        ProductVariationModel(
          id: '3',
          stock: 2,
          price: 20,
          salePrice: 15,
          attributeValues: {'Size': 'Large'},
        ),
      ],
    ),

    ProductModel(
      stock: 2,
      id: 'cake_003',
      name: 'كيكة الجزر',
      description: 'كيكة جزر لذيذة مع جوز الهند، مغطاة بجبنة الكريمة.',
      price: 28.00,
      productType: 'ProductType.size',
      thumbnail: 'assets/images/products/cakes/carrot_cake_1.jpg',
      salePrice: 20.00,
      category: 'cakes',
      imageUrl: 'assets/images/products/cakes/carrot_cake_1.jpg',
      tags: ['كيكات', 'جزر', 'صحي'],
      productAttributes: ProductAttributeModel(
        name: 'Size',
        values: ['Large', 'Medium', 'Small'],
      ),
      productVariations: [
        ProductVariationModel(
          id: '1',
          stock: 5,
          price: 28,
          salePrice: 20,
          attributeValues: {'Size': 'Small'},
        ),
        ProductVariationModel(
          id: '2',
          stock: 3,
          price: 35,
          salePrice: 25,
          attributeValues: {'Size': 'Medium'},
        ),
        ProductVariationModel(
          id: '3',
          stock: 2,
          price: 45,
          salePrice: 30,
          attributeValues: {'Size': 'Large'},
        ),
      ],
    ),
    ProductModel(
      stock: 2,
      id: 'cake_004',
      name: 'كيكة الليمون',
      description: 'كيكة ليمون منعشة مع غلاف سكر ليموني.',
      price: 22.00,
      productType: 'ProductType.size',
      thumbnail: 'assets/images/products/cakes/lemon_cake.jpg',
      salePrice: 20.00,
      category: 'cakes',
      imageUrl: 'assets/images/products/cakes/lemon_cake.jpg',
      tags: ['كيكات', 'ليمون', 'صحي'],
      productAttributes: ProductAttributeModel(
        name: 'Size',
        values: ['Large', 'Medium', 'Small'],
      ),
      productVariations: [
        ProductVariationModel(
          id: '1',
          stock: 4,
          price: 22,
          salePrice: 18,
          attributeValues: {'Size': 'Small'},
        ),
        ProductVariationModel(
          id: '2',
          stock: 3,
          price: 28,
          salePrice: 22,
          attributeValues: {'Size': 'Medium'},
        ),
        ProductVariationModel(
          id: '3',
          stock: 1,
          price: 35,
          salePrice: 28,
          attributeValues: {'Size': 'Large'},
        ),
      ],
    ),
    ProductModel(
      stock: 2,
      id: 'cake_005',
      name: 'كيكة الكراميل المملحة',
      description: 'كيكة كراميل مع طبقة من الكراميل المملح.',
      price: 32.00,
      productType: 'ProductType.size',
      thumbnail: 'assets/images/products/cakes/salted_caramel_cake.jpg',
      salePrice: 20.00,
      category: 'cakes',
      imageUrl: 'assets/images/products/cakes/salted_caramel_cake.jpg',
      tags: ['كيكات', 'كراميل', 'صحي'],
      productAttributes: ProductAttributeModel(
        name: 'Size',
        values: ['Large', 'Medium', 'Small'],
      ),
      productVariations: [
        ProductVariationModel(
          id: '1',
          stock: 6,
          price: 32,
          salePrice: 25,
          attributeValues: {'Size': 'Small'},
        ),
        ProductVariationModel(
          id: '2',
          stock: 4,
          price: 40,
          salePrice: 30,
          attributeValues: {'Size': 'Medium'},
        ),
        ProductVariationModel(
          id: '3',
          stock: 2,
          price: 50,
          salePrice: 35,
          attributeValues: {'Size': 'Large'},
        ),
      ],
    ),
    ProductModel(
      stock: 2,
      id: 'cake_006',
      name: 'كيكة الجبنة بالتوت',
      description: 'تشيز كيك كريمي مع طبقة من التوت الطازج.',
      price: 35.00,
      productType: 'ProductType.size',
      thumbnail: 'assets/images/products/cakes/cheesecake_berries.jpg',
      salePrice: 20.00,
      category: 'cakes',
      imageUrl: 'assets/images/products/cakes/cheesecake_berries.jpg',
      tags: ['كيكات', 'تشيز كيك', 'توت'],
      productAttributes: ProductAttributeModel(
        name: 'Size',
        values: ['Large', 'Medium', 'Small'],
      ),
      productVariations: [
        ProductVariationModel(
          id: '1',
          stock: 7,
          price: 35,
          salePrice: 28,
          attributeValues: {'Size': 'Small'},
        ),
        ProductVariationModel(
          id: '2',
          stock: 5,
          price: 45,
          salePrice: 35,
          attributeValues: {'Size': 'Medium'},
        ),
        ProductVariationModel(
          id: '3',
          stock: 3,
          price: 55,
          salePrice: 40,
          attributeValues: {'Size': 'Large'},
        ),
      ],
    ),
    ProductModel(
      id: 'cake_007',
      name: 'كيكة القهوة',
      description: 'كيكة قهوة مع طبقة من الموكا.',
      price: 27.00,
      category: 'cakes',
      imageUrl: 'assets/images/products/cakes/coffee_cake_1.jpg',
      tags: ['كيكات', 'قهوة', 'صحي'],
      stock: 50,
      productType: 'ProductType.size',
      thumbnail: 'assets/images/products/cakes/coffee_cake_1.jpg',
      salePrice: 24.00,
      productAttributes: ProductAttributeModel(
        name: 'Size',
        values: ['Large', 'Medium', 'Small'],
      ),
      productVariations: [
        ProductVariationModel(
          id: '1',
          stock: 10,
          price: 27,
          salePrice: 22,
          attributeValues: {'Size': 'Small'},
        ),
        ProductVariationModel(
          id: '2',
          stock: 8,
          price: 35,
          salePrice: 28,
          attributeValues: {'Size': 'Medium'},
        ),
        ProductVariationModel(
          id: '3',
          stock: 5,
          price: 45,
          salePrice: 35,
          attributeValues: {'Size': 'Large'},
        ),
      ],
    ),
    ProductModel(
      id: 'cake_008',
      name: 'كيكة الشوكولاتة بالنعناع',
      description: 'كيكة شوكولاتة مع نكهة النعناع المنعشة.',
      price: 29.00,
      category: 'cakes',
      imageUrl: 'assets/images/products/cakes/chocolate_mint_cake.jpg',
      tags: ['كيكات', 'شوكولاتة', 'نعناع'],
      stock: 40,
      productType: 'ProductType.size',
      thumbnail: 'assets/images/products/cakes/chocolate_mint_cake.jpg',
      salePrice: 26.00,
      productAttributes: ProductAttributeModel(
        name: 'Size',
        values: ['Large', 'Medium', 'Small'],
      ),
      productVariations: [
        ProductVariationModel(
          id: '1',
          stock: 12,
          price: 29,
          salePrice: 24,
          attributeValues: {'Size': 'Small'},
        ),
        ProductVariationModel(
          id: '2',
          stock: 10,
          price: 37,
          salePrice: 30,
          attributeValues: {'Size': 'Medium'},
        ),
        ProductVariationModel(
          id: '3',
          stock: 6,
          price: 47,
          salePrice: 37,
          attributeValues: {'Size': 'Large'},
        ),
      ],
    ),
    ProductModel(
      id: 'cake_009',
      name: 'كيكة الفواكه الطازجة',
      description: 'كيكة فواكه طازجة مع كريمة خفيفة.',
      price: 26.00,
      category: 'cakes',
      imageUrl: 'assets/images/products/cakes/fresh_fruit_cake.jpg',
      tags: ['كيكات', 'فواكه', 'صحي'],
      stock: 35,
      productType: 'ProductType.size',
      thumbnail: 'assets/images/products/cakes/fresh_fruit_cake.jpg',
      salePrice: 23.00,
      productAttributes: ProductAttributeModel(
        name: 'Size',
        values: ['Large', 'Medium', 'Small'],
      ),
      productVariations: [
        ProductVariationModel(
          id: '1',
          stock: 15,
          price: 26,
          salePrice: 21,
          attributeValues: {'Size': 'Small'},
        ),
        ProductVariationModel(
          id: '2',
          stock: 12,
          price: 33,
          salePrice: 26,
          attributeValues: {'Size': 'Medium'},
        ),
        ProductVariationModel(
          id: '3',
          stock: 8,
          price: 42,
          salePrice: 33,
          attributeValues: {'Size': 'Large'},
        ),
      ],
    ),
    ProductModel(
      id: 'cake_010',
      name: 'كيكة الكرز الأسود',
      description: 'كيكة شوكولاتة مع طبقة من الكرز الأسود.',
      price: 31.00,
      category: 'cakes',
      imageUrl: 'assets/images/products/cakes/black_forest_cake.jpg',
      tags: ['كيكات', 'شوكولاتة', 'كرز'],
      stock: 30,
      productType: 'ProductType.size',
      thumbnail: 'assets/images/products/cakes/black_forest_cake.jpg',
      salePrice: 28.00,
      productAttributes: ProductAttributeModel(
        name: 'Size',
        values: ['Large', 'Medium', 'Small'],
      ),
      productVariations: [
        ProductVariationModel(
          id: '1',
          stock: 18,
          price: 31,
          salePrice: 25,
          attributeValues: {'Size': 'Small'},
        ),
        ProductVariationModel(
          id: '2',
          stock: 15,
          price: 39,
          salePrice: 31,
          attributeValues: {'Size': 'Medium'},
        ),
        ProductVariationModel(
          id: '3',
          stock: 10,
          price: 49,
          salePrice: 39,
          attributeValues: {'Size': 'Large'},
        ),
      ],
    ),

    // Oriental Desserts
    ProductModel(
      id: 'oriental_001',
      name: 'الكنافة بالقشطة',
      description: 'كنافة مقرمشة محشوة بالقشطة الطازجة.',
      price: 20.00,
      category: 'oriental',
      imageUrl: 'assets/images/products/oriental/kunafa_cream.jpg',
      tags: ['حلويات شرقية', 'كنافة', 'قشطة'],
      stock: 0.5,
      productType: 'ProductType.weight',
      thumbnail: 'assets/images/products/oriental/kunafa_cream.jpg',
      salePrice: 18.00,
      productAttributes: ProductAttributeModel(
        name: 'weight',
        values: ['250g', '500g', '1kg'],
      ),
    ),
    ProductModel(
      id: 'oriental_002',
      name: 'البقلاوة بالفستق',
      description: 'بقلاوة محشوة بالفستق ومغطاة بالقطر.',
      price: 18.00,
      category: 'oriental',
      imageUrl: 'assets/images/products/oriental/baklava_pistachio.jpg',
      tags: ['حلويات شرقية', 'بقلاوة', 'فستق'],
      stock: 5,
      productType: 'ProductType.weight',
      thumbnail: 'assets/images/products/oriental/baklava_pistachio.jpg',
      salePrice: 16.00,
      productAttributes: ProductAttributeModel(
        name: 'weight',
        values: ['250g', '500g', '1kg'],
      ),
    ),
    ProductModel(
        id: 'oriental_003',
        name: 'القطايف بالمكسرات',
        description: 'قطايف محشوة بالمكسرات ومقلية.',
        price: 15.00,
        category: 'oriental',
        imageUrl: 'assets/images/products/oriental/katayef_nuts.jpg',
        tags: ['حلويات شرقية', 'قطايف', 'مكسرات'],
        stock: 70,
        productType: 'ProductType.weight',
        thumbnail: 'assets/images/products/oriental/katayef_nuts.jpg',
        salePrice: 13.00,
        productAttributes: ProductAttributeModel(
          name: 'weight',
          values: ['250g', '500g', '1kg'],
        )),
    ProductModel(
        id: 'oriental_004',
        name: 'البسبوسة بجوز الهند',
        description: 'بسبوسة ناعمة مع جوز الهند وقطر لذيذ.',
        price: 12.00,
        category: 'oriental',
        imageUrl: 'assets/images/products/oriental/basbousa.jpg',
        tags: ['حلويات شرقية', 'بسبوسة', 'جوز الهند'],
        stock: 65,
        productType: 'ProductType.weight',
        thumbnail: 'assets/images/products/oriental/basbousa.jpg',
        salePrice: 10.00,
        productAttributes: ProductAttributeModel(
          name: 'weight',
          values: ['250g', '500g', '1kg'],
        )),
    ProductModel(
        id: 'oriental_005',
        name: 'أم علي',
        description: 'أم علي بالقشطة والمكسرات والزبيب.',
        price: 16.00,
        category: 'oriental',
        imageUrl: 'assets/images/products/oriental/um_ali.jpg',
        tags: ['حلويات شرقية', 'أم علي', 'قشطة'],
        stock: 50,
        productType: 'ProductType.weight',
        thumbnail: 'assets/images/products/oriental/um_ali.jpg',
        salePrice: 14.00,
        productAttributes: ProductAttributeModel(
          name: 'weight',
          values: ['250g', '500g', '1kg'],
        )),
    ProductModel(
        id: 'oriental_006',
        name: 'المهلبيّة بالفستق',
        description: 'مهلبيّة كريمية مع طبقة من الفستق.',
        price: 14.00,
        category: 'oriental',
        imageUrl: 'assets/images/products/oriental/muhalabia_pistachio.jpg',
        tags: ['حلويات شرقية', 'مهلبيّة', 'فستق'],
        stock: 45,
        productType: 'ProductType.weight',
        thumbnail: 'assets/images/products/oriental/muhalabia_pistachio.jpg',
        salePrice: 12.00,
        productAttributes: ProductAttributeModel(
          name: 'weight',
          values: ['250g', '500g', '1kg'],
        )),
    ProductModel(
        id: 'oriental_007',
        name: 'اللقيمات',
        description:
            'لقيمات مقرمشة من الخارج وطرية من الداخل، تقدم مع القطر أو العسل.',
        price: 10.00,
        category: 'oriental',
        imageUrl: 'assets/images/products/oriental/zalabia.jpg',
        tags: ['حلويات شرقية', 'لقيمات', 'عسل'],
        stock: 80,
        productType: 'ProductType.weight',
        thumbnail: 'assets/images/products/oriental/zalabia.jpg',
        salePrice: 8.00,
        productAttributes: ProductAttributeModel(
          name: 'weight',
          values: ['250g', '500g', '1kg'],
        )),
    ProductModel(
        id: 'oriental_008',
        name: 'الغريبة بالسميد',
        description: 'غريبة ناعمة ومقرمشة مصنوعة من السميد.',
        price: 8.00,
        category: 'oriental',
        imageUrl: 'assets/images/products/oriental/ghraybeh.jpg',
        tags: ['حلويات شرقية', 'غريبة', 'سميد'],
        stock: 75,
        productType: 'ProductType.weight',
        thumbnail: 'assets/images/products/oriental/ghraybeh.jpg',
        salePrice: 6.00,
        productAttributes: ProductAttributeModel(
          name: 'weight',
          values: ['250g', '500g', '1kg'],
        )),
    ProductModel(
        id: 'oriental_009',
        name: 'الكنافة النابلسية',
        description: 'كنافة نابلسية مقرمشة مع الجبنة.',
        price: 22.00,
        category: 'oriental',
        imageUrl: 'assets/images/products/oriental/kunafa_cream.jpg',
        tags: ['حلويات شرقية', 'كنافة', 'جبنة'],
        stock: 40,
        productType: 'ProductType.weight',
        thumbnail: 'assets/images/products/oriental/kunafa_cream.jpg',
        salePrice: 20.00,
        productAttributes: ProductAttributeModel(
          name: 'weight',
          values: ['250g', '500g', '1kg'],
        )),
    ProductModel(
        id: 'oriental_010',
        name: 'المعمول بالتمر',
        description: 'معمول محشو بالتمر ومغطى بالسكر البودرة.',
        price: 12.00,
        category: 'oriental',
        imageUrl: 'assets/images/products/oriental/maamoul.jpg',
        tags: ['حلويات شرقية', 'معمول', 'تمر'],
        stock: 60,
        productType: 'ProductType.weight',
        thumbnail: 'assets/images/products/oriental/maamoul.jpg',
        salePrice: 10.00,
        productAttributes: ProductAttributeModel(
          name: 'weight',
          values: ['250g', '500g', '1kg'],
        )),

    // Western Desserts
    ProductModel(
      id: 'western_001',
      name: 'تيراميسو الإيطالي',
      description: 'تيراميسو كلاسيكي مع القهوة والكاكاو.',
      price: 28.00,
      category: 'western',
      imageUrl: 'assets/images/products/western/Italian_tiramisu.jpg',
      tags: ['حلويات غربية', 'تيراميسو', 'قهوة'],
      stock: 25,
      productType: 'western',
      thumbnail: 'assets/images/products/western/Italian_tiramisu.jpg',
      salePrice: 25.00,
    ),
    ProductModel(
      id: 'western_002',
      name: 'كب كيك بالشوكولاتة',
      description: 'كب كيك شوكولاتة مع كريمة زبدة.',
      price: 5.00,
      category: 'western',
      imageUrl: 'assets/images/products/western/chocolate_cupcakes.jpg',
      tags: ['حلويات غربية', 'كب كيك', 'شوكولاتة'],
      stock: 100,
      productType: 'western',
      thumbnail: 'assets/images/products/western/chocolate_cupcakes.jpg',
      salePrice: 4.00,
    ),
    ProductModel(
      id: 'western_003',
      name: 'فطيرة التفاح',
      description: 'فطيرة تفاح بالقرفة والسكر البني.',
      price: 22.00,
      category: 'western',
      imageUrl: 'assets/images/products/western/apple_pie.jpg',
      tags: ['حلويات غربية', 'فطيرة', 'تفاح'],
      stock: 30,
      productType: 'western',
      thumbnail: 'assets/images/products/western/apple_pie.jpg',
      salePrice: 20.00,
    ),
    ProductModel(
      id: 'western_004',
      name: 'كعكة الرغيف بالشوكولاتة',
      description: 'كعكة رغيف شوكولاتة طرية.',
      price: 18.00,
      category: 'western',
      imageUrl: 'assets/images/products/western/chocolate_loaf_cake.jpg',
      tags: ['حلويات غربية', 'كعكة', 'شوكولاتة'],
      stock: 35,
      productType: 'western',
      thumbnail: 'assets/images/products/western/chocolate_loaf_cake.jpg',
      salePrice: 16.00,
    ),
    ProductModel(
      id: 'western_005',
      name: 'كعكة الموز مع الجوز',
      description: 'كعكة موز مع قطع الجوز.',
      price: 20.00,
      category: 'western',
      imageUrl: 'assets/images/products/western/banana_cake_with_walnuts.jpg',
      tags: ['حلويات غربية', 'كعكة', 'موز'],
      stock: 40,
      productType: 'western',
      thumbnail: 'assets/images/products/western/banana_cake_with_walnuts.jpg',
      salePrice: 18.00,
    ),
    ProductModel(
      id: 'western_006',
      name: 'كعكة الفانيليا مع الكراميل',
      description: 'كعكة فانيليا مع طبقة من الكراميل.',
      price: 24.00,
      category: 'western',
      imageUrl: 'assets/images/products/western/vanilla_caramel_cake.jpg',
      tags: ['حلويات غربية', 'كعكة', 'فانيليا'],
      stock: 30,
      productType: 'western',
      thumbnail: 'assets/images/products/western/vanilla_caramel_cake.jpg',
      salePrice: 22.00,
    ),

    // Donuts
    ProductModel(
      id: 'donut_001',
      name: 'دوناتس الشوكولاتة',
      description: 'دوناتس مغطاة بصوص الشوكولاتة الغنية.',
      price: 3.00,
        category: 'donuts',
      imageUrl: 'assets/images/products/donuts/chocolate_donuts.jpg',
      tags: ['دوناتس', 'شوكولاتة'],
      stock: 200,
      productType: 'ProductType.single',
      thumbnail: 'assets/images/products/donuts/chocolate_donuts.jpg',
      salePrice: 2.50,
    ),
    ProductModel(
      id: 'donut_002',
      name: 'دوناتس الفانيليا',
      description: 'دوناتس مغطاة بصوص الفانيليا والسبرينكلز.',
      price: 3.00,
        category: 'donuts',
      imageUrl: 'assets/images/products/donuts/vanilla_donuts.jpg',
      tags: ['دوناتس', 'فانيليا'],
      stock: 180,
      productType: 'ProductType.single',
      thumbnail: 'assets/images/products/donuts/vanilla_donuts.jpg',
      salePrice: 2.50,
    ),
    ProductModel(
      id: 'donut_003',
      name: 'دوناتس الكراميل المملح',
      description: 'دوناتس مغطاة بصوص الكراميل المملح.',
      price: 3.50,
        category: 'donuts',
      imageUrl: 'assets/images/products/donuts/salted_caramel_donuts.jpg',
      tags: ['دوناتس', 'كراميل'],
      stock: 150,
      productType: 'ProductType.single',
      thumbnail: 'assets/images/products/donuts/salted_caramel_donuts.jpg',
      salePrice: 3.00,
    ),
    ProductModel(
      id: 'donut_004',
      name: 'دوناتس الفراولة',
      description: 'دوناتس مغطاة بصوص الفراولة والكريمة.',
      price: 3.50,
        category: 'donuts',
      imageUrl: 'assets/images/products/donuts/strawberry_donuts.jpg',
      tags: ['دوناتس', 'فراولة'],
      stock: 160,
      productType: 'ProductType.single',
      thumbnail: 'assets/images/products/donuts/strawberry_donuts.jpg',
      salePrice: 3.00,
    ),
    ProductModel(
      id: 'donut_005',
      name: 'دوناتس الموز',
      description: 'دوناتس بنكهة الموز مع شوكولاتة.',
      price: 3.00,
        category: 'donuts',
      imageUrl: 'assets/images/products/donuts/banana_donuts.jpg',
      tags: ['دوناتس', 'موز'],
      stock: 170,
      productType: 'ProductType.single',
      thumbnail: 'assets/images/products/donuts/banana_donuts.jpg',
      salePrice: 2.50,
    ),
    ProductModel(
      id: 'donut_006',
      name: 'دوناتس القهوة',
      description: 'دوناتس بنكهة القهوة مع الموكا.',
      price: 3.50,
        category: 'donuts',
      imageUrl: 'assets/images/products/donuts/coffee_donuts.jpg',
      tags: ['دوناتس', 'قهوة'],
      stock: 140,
      productType: 'ProductType.single',
      thumbnail: 'assets/images/products/donuts/coffee_donuts.jpg',
      salePrice: 3.00,
    ),
    ProductModel(
      id: 'donut_008',
      name: 'دوناتس الفستق',
      description: 'دوناتس مغطاة بالفستق والشوكولاتة.',
      price: 4.00,
        category: 'donuts',
      imageUrl: 'assets/images/products/donuts/pistachio_donuts.jpg',
      tags: ['دوناتس', 'فستق'],
      stock: 120,
      productType: 'ProductType.single',
      thumbnail: 'assets/images/products/donuts/pistachio_donuts.jpg',
      salePrice: 3.50,
    ),
    ProductModel(
      id: 'donut_009',
      name: 'دوناتس اللوتس',
      description: 'دوناتس مغطاة بصوص اللوتس والكراميل.',
      price: 3.50,
        category: 'donuts',
      imageUrl: 'assets/images/products/donuts/lotus_donuts_with_caramel.jpg',
      tags: ['دوناتس', 'لوتس'],
      stock: 130,
      productType: 'ProductType.single',
      thumbnail: 'assets/images/products/donuts/lotus_donuts_with_caramel.jpg',
      salePrice: 3.00,
    ),
    ProductModel(
      id: 'donut_010',
      name: 'دوناتس الشوكولاتة البيضاء',
      description: 'دوناتس مغطاة بصوص الشوكولاتة البيضاء.',
      price: 3.50,
        category: 'donuts',
      imageUrl: 'assets/images/products/donuts/white_chocolate_donuts.jpg',
      tags: ['دوناتس', 'شوكولاتة بيضاء'],
      stock: 110,
      productType: 'ProductType.single',
      thumbnail: 'assets/images/products/donuts/white_chocolate_donuts.jpg',
      salePrice: 3.00,
    ),

    // Biscuits & Cookies
    ProductModel(
      id: 'cookie_001',
      name: 'كوكيز الشوكولاتة',
      description: 'كوكيز شوكولاتة طرية مع قطع شوكولاتة.',
      price: 2.00,
     category: 'cookies',
      imageUrl:
          'assets/images/products/cookies/oatmeal_chocolate_chip_cookies.jpg',
      tags: ['بسكويت', 'شوكولاتة'],
      stock: 300,
      productType: 'ProductType.weight',
      thumbnail:
          'assets/images/products/cookies/oatmeal_chocolate_chip_cookies.jpg',
      salePrice: 1.75,
    ),
    ProductModel(
      id: 'cookie_002',
      name: 'كوكيز الزبدة',
      description: 'كوكيز زبدة كلاسيكية مع سكر.',
      price: 1.50,
     category: 'cookies',
      imageUrl: 'assets/images/products/cookies/butter_cookies.jpg',
      tags: ['بسكويت', 'زبدة'],
      stock: 250,
      productType: 'ProductType.weight',
      thumbnail: 'assets/images/products/cookies/butter_cookies.jpg',
      salePrice: 1.25,
    ),
    ProductModel(
      id: 'cookie_003',
      name: 'كوكيز الفانيليا',
      description: 'كوكيز فانيليا مع سكر ملون.',
      price: 1.50,
     category: 'cookies',
      imageUrl: 'assets/images/products/cookies/vanilla_sugar_cookies.jpg',
      tags: ['بسكويت', 'فانيليا'],
      stock: 240,
      productType: 'ProductType.weight',
      thumbnail: 'assets/images/products/cookies/vanilla_sugar_cookies.jpg',
      salePrice: 1.25,
    ),
    ProductModel(
      id: 'cookie_004',
      name: 'كوكيز الشوكولاتة بالنعناع',
      description: 'كوكيز شوكولاتة مع نكهة النعناع.',
      price: 2.00,
     category: 'cookies',
      imageUrl:
          'assets/images/products/cookies/mint_chocolate_chip_cookies.jpg',
      tags: ['بسكويت', 'شوكولاتة', 'نعناع'],
      stock: 220,
      productType: 'ProductType.weight',
      thumbnail:
          'assets/images/products/cookies/mint_chocolate_chip_cookies.jpg',
      salePrice: 1.75,
    ),
    ProductModel(
      id: 'cookie_005',
      name: 'كوكيز الجوز',
      description: 'كوكيز جوز مع القرفة.',
      price: 2.00,
     category: 'cookies',
      imageUrl: 'assets/images/products/cookies/cinnamon_walnut_cookies.jpg',
      tags: ['بسكويت', 'جوز'],
      stock: 210,
      productType: 'ProductType.weight',
      thumbnail: 'assets/images/products/cookies/cinnamon_walnut_cookies.jpg',
      salePrice: 1.75,
    ),
    ProductModel(
      id: 'cookie_006',
      name: 'كوكيز الكراميل المملح',
      description: 'كوكيز كراميل مع ملح البحر.',
      price: 2.50,
     category: 'cookies',
      imageUrl: 'assets/images/products/cookies/salted_caramel_cookies.jpg',
      tags: ['بسكويت', 'كراميل'],
      stock: 200,
      productType: 'ProductType.weight',
      thumbnail: 'assets/images/products/cookies/salted_caramel_cookies.jpg',
      salePrice: 2.25,
    ),
    ProductModel(
      id: 'cookie_007',
      name: 'كوكيز الشوكولاتة البيضاء',
      description: 'كوكيز شوكولاتة بيضاء مع التوت.',
      price: 2.00,
     category: 'cookies',
      imageUrl:
          'assets/images/products/cookies/white_chocolate_raspberry_cookies.jpg',
      tags: ['بسكويت', 'شوكولاتة بيضاء'],
      stock: 190,
      productType: 'ProductType.weight',
      thumbnail:
          'assets/images/products/cookies/white_chocolate_raspberry_cookies.jpg',
      salePrice: 1.75,
    ),
    ProductModel(
      id: 'cookie_008',
      name: 'كوكيز اللوز',
      description: 'كوكيز لوز مع الشوكولاتة.',
      price: 2.00,
     category: 'cookies',
      imageUrl: 'assets/images/products/cookies/chocolate_almond_cookies.jpg',
      tags: ['بسكويت', 'لوز'],
      stock: 180,
      productType: 'ProductType.weight',
      thumbnail: 'assets/images/products/cookies/chocolate_almond_cookies.jpg',
      salePrice: 1.75,
    ),
    ProductModel(
      id: 'cookie_009',
      name: 'كوكيز جوز الهند',
      description: 'كوكيز جوز الهند مع الشوكولاتة.',
      price: 2.00,
     category: 'cookies',
      imageUrl: 'assets/images/products/cookies/chocolate_coconut_cookies.jpg',
      tags: ['بسكويت', 'جوز الهند'],
      stock: 170,
      productType: 'ProductType.weight',
      thumbnail: 'assets/images/products/cookies/chocolate_coconut_cookies.jpg',
      salePrice: 1.75,
    ),
    ProductModel(
      id: 'cookie_010',
      name: 'كوكيز القهوة',
      description: 'كوكيز قهوة مع الشوكولاتة.',
      price: 2.50,
     category: 'cookies',
      imageUrl: 'assets/images/products/cookies/coffee_chocolate_cookies.jpg',
      tags: ['بسكويت', 'قهوة'],
      stock: 160,
      productType: 'ProductType.weight',
      thumbnail: 'assets/images/products/cookies/coffee_chocolate_cookies.jpg',
      salePrice: 2.25,
    ),

    // Healthy Desserts
    ProductModel(
      id: 'healthy_001',
      name: 'كيكة الشوكولاتة الخالية من السكر',
      description: 'كيكة شوكولاتة خالية من السكر مع ستيفيا.',
      price: 25.00,
      category: 'healthy',
      imageUrl: 'assets/images/products/healthy/sugar_free_chocolate_cake.jpg',
      tags: ['صحي', 'شوكولاتة', 'خالي من السكر'],
      stock: 20,
      productType: 'ProductType.size',
      thumbnail: 'assets/images/products/healthy/sugar_free_chocolate_cake.jpg',
      salePrice: 22.00,
    ),
    ProductModel(
      id: 'healthy_002',
      name: 'كوكيز الشوفان بالعسل',
      description: 'كوكيز شوفان مع العسل الطبيعي.',
      price: 2.50,
        category: 'donuts',
      imageUrl: 'assets/images/products/healthy/oatmeal_honey_cookies.jpg',
      tags: ['صحي', 'شوفان', 'عسل'],
      stock: 150,
      productType: 'healthy',
      thumbnail: 'assets/images/products/healthy/oatmeal_honey_cookies.jpg',
      salePrice: 2.25,
    ),
    ProductModel(
      id: 'healthy_003',
      name: 'تشيز كيك نباتي',
      description: 'تشيز كيك نباتي بالتوت الطازج.',
      price: 30.00,
      category: 'healthy',
      imageUrl: 'assets/images/products/healthy/vegan_blueberry_cheesecake.jpg',
      tags: ['صحي', 'تشيز كيك', 'نباتي'],
      stock: 15,
      productType: 'ProductType.size',
      thumbnail:
          'assets/images/products/healthy/vegan_blueberry_cheesecake.jpg',
      salePrice: 28.00,
    ),
    ProductModel(
      id: 'healthy_004',
      name: 'بارفيه التوت',
      description: 'بارفيه التوت مع الزبادي اليوناني.',
      price: 15.00,
      category: 'healthy',
      imageUrl:
          'assets/images/products/healthy/blueberry_parfait_with_greek_yogurt.jpg',
      tags: ['صحي', 'توت', 'زبادي'],
      stock: 50,
      productType: 'ProductType.single',
      thumbnail:
          'assets/images/products/healthy/blueberry_parfait_with_greek_yogurt.jpg',
      salePrice: 13.00,
    ),
    ProductModel(
      id: 'healthy_005',
      name: 'كرات التمر بالمكسرات',
      description: 'كرات التمر مع المكسرات وجوز الهند.',
      price: 10.00,
      category: 'healthy',
      imageUrl: 'assets/images/products/healthy/date_nut_balls.jpg',
      tags: ['صحي', 'تمر', 'مكسرات'],
      stock: 100,
      productType: 'ProductType.weight',
      thumbnail: 'assets/images/products/healthy/date_nut_balls.jpg',
      salePrice: 8.00,
    ),
    ProductModel(
      id: 'healthy_006',
      name: 'كيكة الجزر الخالية من الجلوتين',
      description: 'كيكة جزر خالية من الجلوتين.',
      price: 22.00,
      category: 'healthy',
      imageUrl: 'assets/images/products/healthy/gluten_free_carrot_cake.jpg',
      tags: ['صحي', 'جزر', 'خالي من الجلوتين'],
      stock: 25,
      productType: 'ProductType.size',
      thumbnail: 'assets/images/products/healthy/gluten_free_carrot_cake.jpg',
      salePrice: 20.00,
    ),
    ProductModel(
      id: 'healthy_007',
      name: 'كوكيز الشوكولاتة الخالية من الدقيق',
      description: 'كوكيز شوكولاتة خالية من الدقيق.',
      price: 2.50,
      category: 'healthy',
      imageUrl:
          'assets/images/products/healthy/flourless_chocolate_cookies.jpg',
      tags: ['صحي', 'شوكولاتة', 'خالي من الدقيق'],
      stock: 120,
      productType: 'ProductType.weight',
      thumbnail:
          'assets/images/products/healthy/flourless_chocolate_cookies.jpg',
      salePrice: 2.25,
    ),
    ProductModel(
      id: 'healthy_008',
      name: 'بودنغ الشيا',
      description: 'بودنغ الشيا مع الفواكه الطازجة.',
      price: 12.00,
      category: 'healthy',
      imageUrl: 'assets/images/products/healthy/chia_pudding.jpg',
      tags: ['صحي', 'شيا', 'فواكه'],
      stock: 60,
      productType: 'ProductType.single',
      thumbnail: 'assets/images/products/healthy/chia_pudding.jpg',
      salePrice: 10.00,
    ),
    ProductModel(
      id: 'healthy_009',
      name: 'كعكة الشوفان بالموز',
      description: 'كعكة شوفان مع الموز والعسل.',
      price: 18.00,
      category: 'healthy',
      imageUrl: 'assets/images/products/healthy/oatmeal_banana_cake.jpg',
      tags: ['صحي', 'شوفان', 'موز'],
      stock: 30,
      productType: 'ProductType.weight',
      thumbnail: 'assets/images/products/healthy/oatmeal_banana_cake.jpg',
      salePrice: 16.00,
    ),
    ProductModel(
      id: 'healthy_010',
      name: 'كرات البروتين بالشوكولاتة',
      description: 'كرات بروتين مع الشوكولاتة الداكنة.',
      price: 3.00,
      category: 'healthy',
      imageUrl: 'assets/images/products/healthy/chocolate_protein_balls.jpg',
      tags: ['صحي', 'بروتين', 'شوكولاتة'],
      stock: 200,
      productType: 'ProductType.weight',
      thumbnail: 'assets/images/products/healthy/chocolate_protein_balls.jpg',
      salePrice: 2.75,
    ),
  ];
}
*/

List<ProductModel> initializeDummyData() {
  return [
    ///////////////cakes////////////////////
    ProductModel(
      stock: 2,
      id: 'cake_001',
      name: {
        'ar': 'الكيكة الفانيليا الكلاسيكية',
        'en': 'Classic Vanilla Cake',
      },
      description: {
        'ar': 'كيكة فانيليا طرية وناعمة، مغطاة بكريمة زبدة لذيذة وخفيفة.',
        'en':
            'Soft and fluffy vanilla cake topped with delicious and light buttercream.',
      },
      price: 25.00,
      productType: 'ProductType.size',
      thumbnail: 'assets/images/products/cakes/vanilla_cake.jpg',
      salePrice: 20.00,
      category: 'cakes',
      imageUrl: 'assets/images/products/cakes/vanilla_cake.jpg',
      tags: {
        'ar': ['كيكات', 'فانيليا', 'صحي'],
        'en': ['Cakes', 'Vanilla', 'Healthy'],
      },
      productAttributes: ProductAttributeModel(
        name: 'Size',
        values: ['Large', 'Medium', 'Small'],
      ),
      productVariations: [
        ProductVariationModel(
          id: '1',
          stock: 2,
          price: 10,
          salePrice: 8,
          attributeValues: {'Size': 'Small'},
        ),
        ProductVariationModel(
          id: '2',
          stock: 2,
          price: 10,
          salePrice: 8,
          attributeValues: {'Size': 'Medium'},
        ),
        ProductVariationModel(
          id: '3',
          stock: 2,
          price: 10,
          salePrice: 8,
          attributeValues: {'Size': 'Large'},
        ),
      ],
    ),

    ProductModel(
      stock: 2,
      id: 'cake_002',
      name: {
        'ar': 'كيكة الشوكولاتة الكلاسيكية',
        'en': 'Classic Chocolate Cake',
      },
      description: {
        'ar': 'كيكة شوكولاتة غنية وطرية، مغطاة بصوص الشوكولاتة الساخن.',
        'en': 'Rich and soft chocolate cake topped with hot chocolate sauce.',
      },
      price: 30.00,
      productType: 'ProductType.size',
      thumbnail: 'assets/images/products/cakes/chocolate_cake.jpg',
      salePrice: 20.00,
      category: 'cakes',
      imageUrl: 'assets/images/products/cakes/chocolate_cake.jpg',
      tags: {
        'ar': ['كيكات', 'شوكولاتة', 'صحي'],
        'en': ['Cakes', 'Chocolate', 'Healthy'],
      },
      productAttributes: ProductAttributeModel(
        name: 'Size',
        values: ['Large', 'Medium', 'Small'],
      ),
      productVariations: [
        ProductVariationModel(
          id: '1',
          stock: 2,
          price: 10,
          salePrice: 8,
          attributeValues: {'Size': 'Small'},
        ),
        ProductVariationModel(
          id: '2',
          stock: 2,
          price: 15,
          salePrice: 10,
          attributeValues: {'Size': 'Medium'},
        ),
        ProductVariationModel(
          id: '3',
          stock: 2,
          price: 20,
          salePrice: 15,
          attributeValues: {'Size': 'Large'},
        ),
      ],
    ),

    ProductModel(
      stock: 2,
      id: 'cake_003',
      name: {
        'ar': 'كيكة الجزر',
        'en': 'Carrot Cake',
      },
      description: {
        'ar': 'كيكة جزر لذيذة مع جوز الهند، مغطاة بجبنة الكريمة.',
        'en': 'Delicious carrot cake with coconut, topped with cream cheese.',
      },
      price: 28.00,
      productType: 'ProductType.size',
      thumbnail: 'assets/images/products/cakes/carrot_cake_1.jpg',
      salePrice: 20.00,
      category: 'cakes',
      imageUrl: 'assets/images/products/cakes/carrot_cake_1.jpg',
      tags: {
        'ar': ['كيكات', 'جزر', 'صحي'],
        'en': ['Cakes', 'Carrot', 'Healthy'],
      },
      productAttributes: ProductAttributeModel(
        name: 'Size',
        values: ['Large', 'Medium', 'Small'],
      ),
      productVariations: [
        ProductVariationModel(
          id: '1',
          stock: 5,
          price: 28,
          salePrice: 20,
          attributeValues: {'Size': 'Small'},
        ),
        ProductVariationModel(
          id: '2',
          stock: 3,
          price: 35,
          salePrice: 25,
          attributeValues: {'Size': 'Medium'},
        ),
        ProductVariationModel(
          id: '3',
          stock: 2,
          price: 45,
          salePrice: 30,
          attributeValues: {'Size': 'Large'},
        ),
      ],
    ),

    ProductModel(
      stock: 2,
      id: 'cake_004',
      name: {
        'ar': 'كيكة الليمون',
        'en': 'Lemon Cake',
      },
      description: {
        'ar': 'كيكة ليمون منعشة مع غلاف سكر ليموني.',
        'en': 'Refreshing lemon cake with a lemon sugar glaze.',
      },
      price: 22.00,
      productType: 'ProductType.size',
      thumbnail: 'assets/images/products/cakes/lemon_cake.jpg',
      salePrice: 20.00,
      category: 'cakes',
      imageUrl: 'assets/images/products/cakes/lemon_cake.jpg',
      tags: {
        'ar': ['كيكات', 'ليمون', 'صحي'],
        'en': ['Cakes', 'Lemon', 'Healthy'],
      },
      productAttributes: ProductAttributeModel(
        name: 'Size',
        values: ['Large', 'Medium', 'Small'],
      ),
      productVariations: [
        ProductVariationModel(
          id: '1',
          stock: 4,
          price: 22,
          salePrice: 18,
          attributeValues: {'Size': 'Small'},
        ),
        ProductVariationModel(
          id: '2',
          stock: 3,
          price: 28,
          salePrice: 22,
          attributeValues: {'Size': 'Medium'},
        ),
        ProductVariationModel(
          id: '3',
          stock: 1,
          price: 35,
          salePrice: 28,
          attributeValues: {'Size': 'Large'},
        ),
      ],
    ),

    ProductModel(
      stock: 2,
      id: 'cake_005',
      name: {
        'ar': 'كيكة الكراميل المملحة',
        'en': 'Salted Caramel Cake',
      },
      description: {
        'ar': 'كيكة كراميل مع طبقة من الكراميل المملح.',
        'en': 'Caramel cake with a layer of salted caramel.',
      },
      price: 32.00,
      productType: 'ProductType.size',
      thumbnail: 'assets/images/products/cakes/salted_caramel_cake.jpg',
      salePrice: 20.00,
      category: 'cakes',
      imageUrl: 'assets/images/products/cakes/salted_caramel_cake.jpg',
      tags: {
        'ar': ['كيكات', 'كراميل', 'صحي'],
        'en': ['Cakes', 'Caramel', 'Healthy'],
      },
      productAttributes: ProductAttributeModel(
        name: 'Size',
        values: ['Large', 'Medium', 'Small'],
      ),
      productVariations: [
        ProductVariationModel(
          id: '1',
          stock: 6,
          price: 32,
          salePrice: 25,
          attributeValues: {'Size': 'Small'},
        ),
        ProductVariationModel(
          id: '2',
          stock: 4,
          price: 40,
          salePrice: 30,
          attributeValues: {'Size': 'Medium'},
        ),
        ProductVariationModel(
          id: '3',
          stock: 2,
          price: 50,
          salePrice: 35,
          attributeValues: {'Size': 'Large'},
        ),
      ],
    ),

    ProductModel(
      stock: 2,
      id: 'cake_006',
      name: {
        'ar': 'كيكة الجبنة بالتوت',
        'en': 'Cheesecake with Berries',
      },
      description: {
        'ar': 'تشيز كيك كريمي مع طبقة من التوت الطازج.',
        'en': 'Creamy cheesecake topped with fresh berries.',
      },
      price: 35.00,
      productType: 'ProductType.size',
      thumbnail: 'assets/images/products/cakes/cheesecake_berries.jpg',
      salePrice: 20.00,
      category: 'cakes',
      imageUrl: 'assets/images/products/cakes/cheesecake_berries.jpg',
      tags: {
        'ar': ['كيكات', 'تشيز كيك', 'توت'],
        'en': ['Cakes', 'Cheesecake', 'Berries'],
      },
      productAttributes: ProductAttributeModel(
        name: 'Size',
        values: ['Large', 'Medium', 'Small'],
      ),
      productVariations: [
        ProductVariationModel(
          id: '1',
          stock: 7,
          price: 35,
          salePrice: 28,
          attributeValues: {'Size': 'Small'},
        ),
        ProductVariationModel(
          id: '2',
          stock: 5,
          price: 45,
          salePrice: 35,
          attributeValues: {'Size': 'Medium'},
        ),
        ProductVariationModel(
          id: '3',
          stock: 3,
          price: 55,
          salePrice: 40,
          attributeValues: {'Size': 'Large'},
        ),
      ],
    ),

    ProductModel(
      id: 'cake_007',
      name: {
        'ar': 'كيكة القهوة',
        'en': 'Coffee Cake',
      },
      description: {
        'ar': 'كيكة قهوة مع طبقة من الموكا.',
        'en': 'Coffee cake with a layer of mocha.',
      },
      price: 27.00,
      category: 'cakes',
      imageUrl: 'assets/images/products/cakes/coffee_cake_1.jpg',
      tags: {
        'ar': ['كيكات', 'قهوة', 'صحي'],
        'en': ['Cakes', 'Coffee', 'Healthy'],
      },
      stock: 50,
      productType: 'ProductType.size',
      thumbnail: 'assets/images/products/cakes/coffee_cake_1.jpg',
      salePrice: 24.00,
      productAttributes: ProductAttributeModel(
        name: 'Size',
        values: ['Large', 'Medium', 'Small'],
      ),
      productVariations: [
        ProductVariationModel(
          id: '1',
          stock: 10,
          price: 27,
          salePrice: 22,
          attributeValues: {'Size': 'Small'},
        ),
        ProductVariationModel(
          id: '2',
          stock: 8,
          price: 35,
          salePrice: 28,
          attributeValues: {'Size': 'Medium'},
        ),
        ProductVariationModel(
          id: '3',
          stock: 5,
          price: 45,
          salePrice: 35,
          attributeValues: {'Size': 'Large'},
        ),
      ],
    ),

    ProductModel(
      id: 'cake_008',
      name: {
        'ar': 'كيكة الشوكولاتة بالنعناع',
        'en': 'Chocolate Mint Cake',
      },
      description: {
        'ar': 'كيكة شوكولاتة مع نكهة النعناع المنعشة.',
        'en': 'Chocolate cake with refreshing mint flavor.',
      },
      price: 29.00,
      category: 'cakes',
      imageUrl: 'assets/images/products/cakes/chocolate_mint_cake.jpg',
      tags: {
        'ar': ['كيكات', 'شوكولاتة', 'نعناع'],
        'en': ['Cakes', 'Chocolate', 'Mint'],
      },
      stock: 40,
      productType: 'ProductType.size',
      thumbnail: 'assets/images/products/cakes/chocolate_mint_cake.jpg',
      salePrice: 26.00,
      productAttributes: ProductAttributeModel(
        name: 'Size',
        values: ['Large', 'Medium', 'Small'],
      ),
      productVariations: [
        ProductVariationModel(
          id: '1',
          stock: 12,
          price: 29,
          salePrice: 24,
          attributeValues: {'Size': 'Small'},
        ),
        ProductVariationModel(
          id: '2',
          stock: 10,
          price: 37,
          salePrice: 30,
          attributeValues: {'Size': 'Medium'},
        ),
        ProductVariationModel(
          id: '3',
          stock: 6,
          price: 47,
          salePrice: 37,
          attributeValues: {'Size': 'Large'},
        ),
      ],
    ),

    ProductModel(
      id: 'cake_009',
      name: {
        'ar': 'كيكة الفواكه الطازجة',
        'en': 'Fresh Fruit Cake',
      },
      description: {
        'ar': 'كيكة فواكه طازجة مع كريمة خفيفة.',
        'en': 'Fresh fruit cake with light cream.',
      },
      price: 26.00,
      category: 'cakes',
      imageUrl: 'assets/images/products/cakes/fresh_fruit_cake.jpg',
      tags: {
        'ar': ['كيكات', 'فواكه', 'صحي'],
        'en': ['Cakes', 'Fruits', 'Healthy'],
      },
      stock: 35,
      productType: 'ProductType.size',
      thumbnail: 'assets/images/products/cakes/fresh_fruit_cake.jpg',
      salePrice: 23.00,
      productAttributes: ProductAttributeModel(
        name: 'Size',
        values: ['Large', 'Medium', 'Small'],
      ),
      productVariations: [
        ProductVariationModel(
          id: '1',
          stock: 15,
          price: 26,
          salePrice: 21,
          attributeValues: {'Size': 'Small'},
        ),
        ProductVariationModel(
          id: '2',
          stock: 12,
          price: 33,
          salePrice: 26,
          attributeValues: {'Size': 'Medium'},
        ),
        ProductVariationModel(
          id: '3',
          stock: 8,
          price: 42,
          salePrice: 33,
          attributeValues: {'Size': 'Large'},
        ),
      ],
    ),

    ProductModel(
      id: 'cake_010',
      name: {
        'ar': 'كيكة الكرز الأسود',
        'en': 'Black Forest Cake',
      },
      description: {
        'ar': 'كيكة شوكولاتة مع طبقة من الكرز الأسود.',
        'en': 'Chocolate cake with a layer of black cherries.',
      },
      price: 31.00,
      category: 'cakes',
      imageUrl: 'assets/images/products/cakes/black_forest_cake.jpg',
      tags: {
        'ar': ['كيكات', 'شوكولاتة', 'كرز'],
        'en': ['Cakes', 'Chocolate', 'Cherry'],
      },
      stock: 30,
      productType: 'ProductType.size',
      thumbnail: 'assets/images/products/cakes/black_forest_cake.jpg',
      salePrice: 28.00,
      productAttributes: ProductAttributeModel(
        name: 'Size',
        values: ['Large', 'Medium', 'Small'],
      ),
      productVariations: [
        ProductVariationModel(
          id: '1',
          stock: 18,
          price: 31,
          salePrice: 25,
          attributeValues: {'Size': 'Small'},
        ),
        ProductVariationModel(
          id: '2',
          stock: 15,
          price: 39,
          salePrice: 31,
          attributeValues: {'Size': 'Medium'},
        ),
        ProductVariationModel(
          id: '3',
          stock: 10,
          price: 49,
          salePrice: 39,
          attributeValues: {'Size': 'Large'},
        ),
      ],
    ),
/////////////////oriental desserts////////////////////

    ProductModel(
      id: 'oriental_001',
      name: {
        'ar': 'الكنافة بالقشطة',
        'en': 'Kunafa with Cream',
      },
      description: {
        'ar': 'كنافة مقرمشة محشوة بالقشطة الطازجة.',
        'en': 'Crispy kunafa filled with fresh cream.',
      },
      price: 20.00,
      category: 'oriental',
      imageUrl: 'assets/images/products/oriental/kunafa_cream.jpg',
      tags: {
        'ar': ['حلويات شرقية', 'كنافة', 'قشطة'],
        'en': ['Oriental Desserts', 'Kunafa', 'Cream'],
      },
      stock: 0.5,
      productType: 'ProductType.weight',
      thumbnail: 'assets/images/products/oriental/kunafa_cream.jpg',
      salePrice: 18.00,
      productAttributes: ProductAttributeModel(
        name: 'weight',
        values: ['250g', '500g', '1kg'],
      ),
    ),

    ProductModel(
      id: 'oriental_002',
      name: {
        'ar': 'البقلاوة بالفستق',
        'en': 'Pistachio Baklava',
      },
      description: {
        'ar': 'بقلاوة محشوة بالفستق ومغطاة بالقطر.',
        'en': 'Baklava filled with pistachios and topped with syrup.',
      },
      price: 18.00,
      category: 'oriental',
      imageUrl: 'assets/images/products/oriental/baklava_pistachio.jpg',
      tags: {
        'ar': ['حلويات شرقية', 'بقلاوة', 'فستق'],
        'en': ['Oriental Desserts', 'Baklava', 'Pistachio'],
      },
      stock: 5,
      productType: 'ProductType.weight',
      thumbnail: 'assets/images/products/oriental/baklava_pistachio.jpg',
      salePrice: 16.00,
      productAttributes: ProductAttributeModel(
        name: 'weight',
        values: ['250g', '500g', '1kg'],
      ),
    ),
    ProductModel(
      id: 'oriental_003',
      name: {
        'ar': 'القطايف بالمكسرات',
        'en': 'Katayef with Nuts',
      },
      description: {
        'ar': 'قطايف محشوة بالمكسرات ومقلية.',
        'en': 'Katayef stuffed with nuts and fried.',
      },
      price: 15.00,
      category: 'oriental',
      imageUrl: 'assets/images/products/oriental/katayef_nuts.jpg',
      tags: {
        'ar': ['حلويات شرقية', 'قطايف', 'مكسرات'],
        'en': ['Oriental Desserts', 'Katayef', 'Nuts'],
      },
      stock: 70,
      productType: 'ProductType.weight',
      thumbnail: 'assets/images/products/oriental/katayef_nuts.jpg',
      salePrice: 13.00,
      productAttributes: ProductAttributeModel(
        name: 'weight',
        values: ['250g', '500g', '1kg'],
      ),
    ),
    ProductModel(
      id: 'oriental_004',
      name: {
        'ar': 'البسبوسة بجوز الهند',
        'en': 'Basbousa with Coconut',
      },
      description: {
        'ar': 'بسبوسة ناعمة مع جوز الهند وقطر لذيذ.',
        'en': 'Soft basbousa with coconut and delicious syrup.',
      },
      price: 12.00,
      category: 'oriental',
      imageUrl: 'assets/images/products/oriental/basbousa.jpg',
      tags: {
        'ar': ['حلويات شرقية', 'بسبوسة', 'جوز الهند'],
        'en': ['Oriental Desserts', 'Basbousa', 'Coconut'],
      },
      stock: 65,
      productType: 'ProductType.weight',
      thumbnail: 'assets/images/products/oriental/basbousa.jpg',
      salePrice: 10.00,
      productAttributes: ProductAttributeModel(
        name: 'weight',
        values: ['250g', '500g', '1kg'],
      ),
    ),
    ProductModel(
      id: 'oriental_005',
      name: {
        'ar': 'أم علي',
        'en': 'Umm Ali',
      },
      description: {
        'ar': 'أم علي بالقشطة والمكسرات والزبيب.',
        'en': 'Umm Ali with cream, nuts, and raisins.',
      },
      price: 16.00,
      category: 'oriental',
      imageUrl: 'assets/images/products/oriental/um_ali.jpg',
      tags: {
        'ar': ['حلويات شرقية', 'أم علي', 'قشطة'],
        'en': ['Oriental Desserts', 'Umm Ali', 'Cream'],
      },
      stock: 50,
      productType: 'ProductType.weight',
      thumbnail: 'assets/images/products/oriental/um_ali.jpg',
      salePrice: 14.00,
      productAttributes: ProductAttributeModel(
        name: 'weight',
        values: ['250g', '500g', '1kg'],
      ),
    ),
    ProductModel(
      id: 'oriental_006',
      name: {
        'ar': 'المهلبيّة بالفستق',
        'en': 'Muhalabia with Pistachio',
      },
      description: {
        'ar': 'مهلبيّة كريمية مع طبقة من الفستق.',
        'en': 'Creamy muhalabia topped with pistachios.',
      },
      price: 14.00,
      category: 'oriental',
      imageUrl: 'assets/images/products/oriental/muhalabia_pistachio.jpg',
      tags: {
        'ar': ['حلويات شرقية', 'مهلبيّة', 'فستق'],
        'en': ['Oriental Desserts', 'Muhalabia', 'Pistachio'],
      },
      stock: 45,
      productType: 'ProductType.weight',
      thumbnail: 'assets/images/products/oriental/muhalabia_pistachio.jpg',
      salePrice: 12.00,
      productAttributes: ProductAttributeModel(
        name: 'weight',
        values: ['250g', '500g', '1kg'],
      ),
    ),
    ProductModel(
      id: 'oriental_007',
      name: {
        'ar': 'اللقيمات',
        'en': 'Luqaimat',
      },
      description: {
        'ar':
            'لقيمات مقرمشة من الخارج وطرية من الداخل، تقدم مع القطر أو العسل.',
        'en':
            'Crispy on the outside and soft on the inside, served with syrup or honey.',
      },
      price: 10.00,
      category: 'oriental',
      imageUrl: 'assets/images/products/oriental/zalabia.jpg',
      tags: {
        'ar': ['حلويات شرقية', 'لقيمات', 'عسل'],
        'en': ['Oriental Desserts', 'Luqaimat', 'Honey'],
      },
      stock: 80,
      productType: 'ProductType.weight',
      thumbnail: 'assets/images/products/oriental/zalabia.jpg',
      salePrice: 8.00,
      productAttributes: ProductAttributeModel(
        name: 'weight',
        values: ['250g', '500g', '1kg'],
      ),
    ),
    ProductModel(
      id: 'oriental_008',
      name: {
        'ar': 'الغريبة بالسميد',
        'en': 'Ghraybeh with Semolina',
      },
      description: {
        'ar': 'غريبة ناعمة ومقرمشة مصنوعة من السميد.',
        'en': 'Soft and crunchy ghraybeh made from semolina.',
      },
      price: 8.00,
      category: 'oriental',
      imageUrl: 'assets/images/products/oriental/ghraybeh.jpg',
      tags: {
        'ar': ['حلويات شرقية', 'غريبة', 'سميد'],
        'en': ['Oriental Desserts', 'Ghraybeh', 'Semolina'],
      },
      stock: 75,
      productType: 'ProductType.weight',
      thumbnail: 'assets/images/products/oriental/ghraybeh.jpg',
      salePrice: 6.00,
      productAttributes: ProductAttributeModel(
        name: 'weight',
        values: ['250g', '500g', '1kg'],
      ),
    ),
    ProductModel(
      id: 'oriental_009',
      name: {
        'ar': 'الكنافة النابلسية',
        'en': 'Nabulsi Kunafa',
      },
      description: {
        'ar': 'كنافة نابلسية مقرمشة مع الجبنة.',
        'en': 'Crispy Nabulsi kunafa with cheese.',
      },
      price: 22.00,
      category: 'oriental',
      imageUrl: 'assets/images/products/oriental/kunafa_cream.jpg',
      tags: {
        'ar': ['حلويات شرقية', 'كنافة', 'جبنة'],
        'en': ['Oriental Desserts', 'Kunafa', 'Cheese'],
      },
      stock: 40,
      productType: 'ProductType.weight',
      thumbnail: 'assets/images/products/oriental/kunafa_cream.jpg',
      salePrice: 20.00,
      productAttributes: ProductAttributeModel(
        name: 'weight',
        values: ['250g', '500g', '1kg'],
      ),
    ),
    ProductModel(
      id: 'oriental_010',
      name: {
        'ar': 'المعمول بالتمر',
        'en': 'Date Maamoul',
      },
      description: {
        'ar': 'معمول محشو بالتمر ومغطى بالسكر البودرة.',
        'en': 'Maamoul stuffed with dates and dusted with powdered sugar.',
      },
      price: 12.00,
      category: 'oriental',
      imageUrl: 'assets/images/products/oriental/maamoul.jpg',
      tags: {
        'ar': ['حلويات شرقية', 'معمول', 'تمر'],
        'en': ['Oriental Desserts', 'Maamoul', 'Dates'],
      },
      stock: 60,
      productType: 'ProductType.weight',
      thumbnail: 'assets/images/products/oriental/maamoul.jpg',
      salePrice: 10.00,
      productAttributes: ProductAttributeModel(
        name: 'weight',
        values: ['250g', '500g', '1kg'],
      ),
    ),

    ///////////////////western desserts////////////////////
    ProductModel(
      id: 'western_001',
      name: {
        'ar': 'تيراميسو الإيطالي',
        'en': 'Italian Tiramisu',
      },
      description: {
        'ar': 'تيراميسو كلاسيكي مع القهوة والكاكاو.',
        'en': 'Classic tiramisu with coffee and cocoa.',
      },
      price: 28.00,
      category: 'western',
      imageUrl: 'assets/images/products/western/Italian_tiramisu.jpg',
      tags: {
        'ar': ['حلويات غربية', 'تيراميسو', 'قهوة'],
        'en': ['Western Desserts', 'Tiramisu', 'Coffee'],
      },
      stock: 25,
      productType: 'ProductType.size',
      thumbnail: 'assets/images/products/western/Italian_tiramisu.jpg',
      salePrice: 25.00,
      productAttributes: ProductAttributeModel(
        name: 'Size',
        values: ['Large', 'Medium', 'Small'],
      ),
      productVariations: [
        ProductVariationModel(
          id: '1',
          stock: 5,
          price: 28,
          salePrice: 25,
          attributeValues: {'Size': 'Small'},
        ),
        ProductVariationModel(
          id: '2',
          stock: 10,
          price: 35,
          salePrice: 30,
          attributeValues: {'Size': 'Medium'},
        ),
        ProductVariationModel(
          id: '3',
          stock: 15,
          price: 45,
          salePrice: 40,
          attributeValues: {'Size': 'Large'},
        ),
      ],
    ),
    ProductModel(
      id: 'western_002',
      name: {
        'ar': 'كب كيك بالشوكولاتة',
        'en': 'Chocolate Cupcakes',
      },
      description: {
        'ar': 'كب كيك شوكولاتة مع كريمة زبدة.',
        'en': 'Chocolate cupcakes with buttercream frosting.',
      },
      price: 5.00,
      category: 'western',
      imageUrl: 'assets/images/products/western/chocolate_cupcakes.jpg',
      tags: {
        'ar': ['حلويات غربية', 'كب كيك', 'شوكولاتة'],
        'en': ['Western Desserts', 'Cupcakes', 'Chocolate'],
      },
      stock: 100,
      productType: 'ProductType.size',
      thumbnail: 'assets/images/products/western/chocolate_cupcakes.jpg',
      salePrice: 4.00,
      productAttributes: ProductAttributeModel(
        name: 'Size',
        values: ['Large', 'Medium', 'Small'],
      ),
      productVariations: [
        ProductVariationModel(
          id: '1',
          stock: 20,
          price: 5,
          salePrice: 4,
          attributeValues: {'Size': 'Small'},
        ),
        ProductVariationModel(
          id: '2',
          stock: 30,
          price: 7,
          salePrice: 6,
          attributeValues: {'Size': 'Medium'},
        ),
        ProductVariationModel(
          id: '3',
          stock: 50,
          price: 10,
          salePrice: 8,
          attributeValues: {'Size': 'Large'},
        ),
      ],
    ),
    ProductModel(
      id: 'western_003',
      name: {
        'ar': 'فطيرة التفاح',
        'en': 'Apple Pie',
      },
      description: {
        'ar': 'فطيرة تفاح بالقرفة والسكر البني.',
        'en': 'Apple pie with cinnamon and brown sugar.',
      },
      price: 22.00,
      category: 'western',
      imageUrl: 'assets/images/products/western/apple_pie.jpg',
      tags: {
        'ar': ['حلويات غربية', 'فطيرة', 'تفاح'],
        'en': ['Western Desserts', 'Pie', 'Apple'],
      },
      stock: 30,
      productType: 'ProductType.size',
      thumbnail: 'assets/images/products/western/apple_pie.jpg',
      salePrice: 20.00,
      productAttributes: ProductAttributeModel(
        name: 'Size',
        values: ['Large', 'Medium', 'Small'],
      ),
      productVariations: [
        ProductVariationModel(
          id: '1',
          stock: 5,
          price: 22,
          salePrice: 20,
          attributeValues: {'Size': 'Small'},
        ),
        ProductVariationModel(
          id: '2',
          stock: 10,
          price: 28,
          salePrice: 25,
          attributeValues: {'Size': 'Medium'},
        ),
        ProductVariationModel(
          id: '3',
          stock: 15,
          price: 35,
          salePrice: 30,
          attributeValues: {'Size': 'Large'},
        ),
      ],
    ),
    ProductModel(
      id: 'western_004',
      name: {
        'ar': 'كعكة الرغيف بالشوكولاتة',
        'en': 'Chocolate Loaf Cake',
      },
      description: {
        'ar': 'كعكة رغيف شوكولاتة طرية.',
        'en': 'Soft chocolate loaf cake.',
      },
      price: 18.00,
      category: 'western',
      imageUrl: 'assets/images/products/western/chocolate_loaf_cake.jpg',
      tags: {
        'ar': ['حلويات غربية', 'كعكة', 'شوكولاتة'],
        'en': ['Western Desserts', 'Cake', 'Chocolate'],
      },
      stock: 35,
      productType: 'ProductType.size',
      thumbnail: 'assets/images/products/western/chocolate_loaf_cake.jpg',
      salePrice: 16.00,
      productAttributes: ProductAttributeModel(
        name: 'Size',
        values: ['Large', 'Medium', 'Small'],
      ),
      productVariations: [
        ProductVariationModel(
          id: '1',
          stock: 5,
          price: 18,
          salePrice: 16,
          attributeValues: {'Size': 'Small'},
        ),
        ProductVariationModel(
          id: '2',
          stock: 10,
          price: 25,
          salePrice: 20,
          attributeValues: {'Size': 'Medium'},
        ),
        ProductVariationModel(
          id: '3',
          stock: 20,
          price: 35,
          salePrice: 30,
          attributeValues: {'Size': 'Large'},
        ),
      ],
    ),
    ProductModel(
      id: 'western_005',
      name: {
        'ar': 'كعكة الموز مع الجوز',
        'en': 'Banana Walnut Cake',
      },
      description: {
        'ar': 'كعكة موز مع قطع الجوز.',
        'en': 'Banana cake with walnut pieces.',
      },
      price: 20.00,
      category: 'western',
      imageUrl: 'assets/images/products/western/banana_cake_with_walnuts.jpg',
      tags: {
        'ar': ['حلويات غربية', 'كعكة', 'موز'],
        'en': ['Western Desserts', 'Cake', 'Banana'],
      },
      stock: 40,
      productType: 'ProductType.size',
      thumbnail: 'assets/images/products/western/banana_cake_with_walnuts.jpg',
      salePrice: 18.00,
      productAttributes: ProductAttributeModel(
        name: 'Size',
        values: ['Large', 'Medium', 'Small'],
      ),
      productVariations: [
        ProductVariationModel(
          id: '1',
          stock: 5,
          price: 20,
          salePrice: 18,
          attributeValues: {'Size': 'Small'},
        ),
        ProductVariationModel(
          id: '2',
          stock: 10,
          price: 25,
          salePrice: 22,
          attributeValues: {'Size': 'Medium'},
        ),
        ProductVariationModel(
          id: '3',
          stock: 25,
          price: 35,
          salePrice: 30,
          attributeValues: {'Size': 'Large'},
        ),
      ],
    ),
    ProductModel(
      id: 'western_006',
      name: {
        'ar': 'كعكة الفانيليا مع الكراميل',
        'en': 'Vanilla Caramel Cake',
      },
      description: {
        'ar': 'كعكة فانيليا مع طبقة من الكراميل.',
        'en': 'Vanilla cake with a layer of caramel.',
      },
      price: 24.00,
      category: 'western',
      imageUrl: 'assets/images/products/western/vanilla_caramel_cake.jpg',
      tags: {
        'ar': ['حلويات غربية', 'كعكة', 'فانيليا'],
        'en': ['Western Desserts', 'Cake', 'Vanilla'],
      },
      stock: 30,
      productType: 'ProductType.size',
      thumbnail: 'assets/images/products/western/vanilla_caramel_cake.jpg',
      salePrice: 22.00,
      productAttributes: ProductAttributeModel(
        name: 'Size',
        values: ['Large', 'Medium', 'Small'],
      ),
      productVariations: [
        ProductVariationModel(
          id: '1',
          stock: 5,
          price: 24,
          salePrice: 22,
          attributeValues: {'Size': 'Small'},
        ),
        ProductVariationModel(
          id: '2',
          stock: 10,
          price: 30,
          salePrice: 25,
          attributeValues: {'Size': 'Medium'},
        ),
        ProductVariationModel(
          id: '3',
          stock: 15,
          price: 40,
          salePrice: 35,
          attributeValues: {'Size': 'Large'},
        ),
      ],
    ),

    /////////////// donuts //////////////////
    ProductModel(
      id: 'donut_001',
      name: {
        'ar': 'دوناتس الشوكولاتة',
        'en': 'Chocolate Donuts',
      },
      description: {
        'ar': 'دوناتس مغطاة بصوص الشوكولاتة الغنية.',
        'en': 'Donuts covered with rich chocolate glaze.',
      },
      price: 3.00,
      category: 'donuts',
      imageUrl: 'assets/images/products/donuts/chocolate_donuts.jpg',
      tags: {
        'ar': ['دوناتس', 'شوكولاتة'],
        'en': ['Donuts', 'Chocolate'],
      },
      stock: 200,
      productType: 'ProductType.single',
      thumbnail: 'assets/images/products/donuts/chocolate_donuts.jpg',
      salePrice: 2.50,
    ),
    ProductModel(
      id: 'donut_002',
      name: {
        'ar': 'دوناتس الفانيليا',
        'en': 'Vanilla Donuts',
      },
      description: {
        'ar': 'دوناتس مغطاة بصوص الفانيليا والسبرينكلز.',
        'en': 'Vanilla glazed donuts with sprinkles.',
      },
      price: 3.00,
      category: 'donuts',
      imageUrl: 'assets/images/products/donuts/vanilla_donuts.jpg',
      tags: {
        'ar': ['دوناتس', 'فانيليا'],
        'en': ['Donuts', 'Vanilla'],
      },
      stock: 180,
      productType: 'ProductType.single',
      thumbnail: 'assets/images/products/donuts/vanilla_donuts.jpg',
      salePrice: 2.50,
    ),
    ProductModel(
      id: 'donut_003',
      name: {
        'ar': 'دوناتس الكراميل المملح',
        'en': 'Salted Caramel Donuts',
      },
      description: {
        'ar': 'دوناتس مغطاة بصوص الكراميل المملح.',
        'en': 'Donuts topped with salted caramel glaze.',
      },
      price: 3.50,
      category: 'donuts',
      imageUrl: 'assets/images/products/donuts/salted_caramel_donuts.jpg',
      tags: {
        'ar': ['دوناتس', 'كراميل'],
        'en': ['Donuts', 'Caramel'],
      },
      stock: 150,
      productType: 'ProductType.single',
      thumbnail: 'assets/images/products/donuts/salted_caramel_donuts.jpg',
      salePrice: 3.00,
    ),
    ProductModel(
      id: 'donut_004',
      name: {
        'ar': 'دوناتس الفراولة',
        'en': 'Strawberry Donuts',
      },
      description: {
        'ar': 'دوناتس مغطاة بصوص الفراولة والكريمة.',
        'en': 'Donuts topped with strawberry glaze and cream.',
      },
      price: 3.50,
      category: 'donuts',
      imageUrl: 'assets/images/products/donuts/strawberry_donuts.jpg',
      tags: {
        'ar': ['دوناتس', 'فراولة'],
        'en': ['Donuts', 'Strawberry'],
      },
      stock: 160,
      productType: 'ProductType.single',
      thumbnail: 'assets/images/products/donuts/strawberry_donuts.jpg',
      salePrice: 3.00,
    ),
    ProductModel(
      id: 'donut_005',
      name: {
        'ar': 'دوناتس الموز',
        'en': 'Banana Donuts',
      },
      description: {
        'ar': 'دوناتس بنكهة الموز مع شوكولاتة.',
        'en': 'Banana-flavored donuts with chocolate.',
      },
      price: 3.00,
      category: 'donuts',
      imageUrl: 'assets/images/products/donuts/banana_donuts.jpg',
      tags: {
        'ar': ['دوناتس', 'موز'],
        'en': ['Donuts', 'Banana'],
      },
      stock: 170,
      productType: 'ProductType.single',
      thumbnail: 'assets/images/products/donuts/banana_donuts.jpg',
      salePrice: 2.50,
    ),
    ProductModel(
      id: 'donut_006',
      name: {
        'ar': 'دوناتس القهوة',
        'en': 'Coffee Donuts',
      },
      description: {
        'ar': 'دوناتس بنكهة القهوة مع الموكا.',
        'en': 'Coffee-flavored donuts with mocha.',
      },
      price: 3.50,
      category: 'donuts',
      imageUrl: 'assets/images/products/donuts/coffee_donuts.jpg',
      tags: {
        'ar': ['دوناتس', 'قهوة'],
        'en': ['Donuts', 'Coffee'],
      },
      stock: 140,
      productType: 'ProductType.single',
      thumbnail: 'assets/images/products/donuts/coffee_donuts.jpg',
      salePrice: 3.00,
    ),
    ProductModel(
      id: 'donut_008',
      name: {
        'ar': 'دوناتس الفستق',
        'en': 'Pistachio Donuts',
      },
      description: {
        'ar': 'دوناتس مغطاة بالفستق والشوكولاتة.',
        'en': 'Donuts topped with pistachios and chocolate.',
      },
      price: 4.00,
      category: 'donuts',
      imageUrl: 'assets/images/products/donuts/pistachio_donuts.jpg',
      tags: {
        'ar': ['دوناتس', 'فستق'],
        'en': ['Donuts', 'Pistachio'],
      },
      stock: 120,
      productType: 'ProductType.single',
      thumbnail: 'assets/images/products/donuts/pistachio_donuts.jpg',
      salePrice: 3.50,
    ),
    ProductModel(
      id: 'donut_009',
      name: {
        'ar': 'دوناتس اللوتس',
        'en': 'Lotus Donuts',
      },
      description: {
        'ar': 'دوناتس مغطاة بصوص اللوتس والكراميل.',
        'en': 'Donuts topped with lotus glaze and caramel.',
      },
      price: 3.50,
      category: 'donuts',
      imageUrl: 'assets/images/products/donuts/lotus_donuts_with_caramel.jpg',
      tags: {
        'ar': ['دوناتس', 'لوتس'],
        'en': ['Donuts', 'Lotus'],
      },
      stock: 130,
      productType: 'ProductType.single',
      thumbnail: 'assets/images/products/donuts/lotus_donuts_with_caramel.jpg',
      salePrice: 3.00,
    ),
    ProductModel(
      id: 'donut_010',
      name: {
        'ar': 'دوناتس الشوكولاتة البيضاء',
        'en': 'White Chocolate Donuts',
      },
      description: {
        'ar': 'دوناتس مغطاة بصوص الشوكولاتة البيضاء.',
        'en': 'Donuts topped with white chocolate glaze.',
      },
      price: 3.50,
      category: 'donuts',
      imageUrl: 'assets/images/products/donuts/white_chocolate_donuts.jpg',
      tags: {
        'ar': ['دوناتس', 'شوكولاتة بيضاء'],
        'en': ['Donuts', 'White Chocolate'],
      },
      stock: 110,
      productType: 'ProductType.single',
      thumbnail: 'assets/images/products/donuts/white_chocolate_donuts.jpg',
      salePrice: 3.00,
    ),

///////////////////////////cookies/////////////////////////////////////

    ProductModel(
      id: 'cookie_001',
      name: {
        'ar': 'كوكيز الشوكولاتة',
        'en': 'Chocolate Cookies',
      },
      description: {
        'ar': 'كوكيز شوكولاتة طرية مع قطع شوكولاتة.',
        'en': 'Soft chocolate cookies with chocolate chunks.',
      },
      price: 2.00,
      category: 'cookies',
      imageUrl:
          'assets/images/products/cookies/oatmeal_chocolate_chip_cookies.jpg',
      tags: {
        'ar': ['بسكويت', 'شوكولاتة'],
        'en': ['Cookies', 'Chocolate'],
      },
      stock: 300,
      productType: 'ProductType.weight',
      thumbnail:
          'assets/images/products/cookies/oatmeal_chocolate_chip_cookies.jpg',
      salePrice: 1.75,
    ),
    ProductModel(
      id: 'cookie_002',
      name: {
        'ar': 'كوكيز الزبدة',
        'en': 'Butter Cookies',
      },
      description: {
        'ar': 'كوكيز زبدة كلاسيكية مع سكر.',
        'en': 'Classic butter cookies with sugar.',
      },
      price: 1.50,
      category: 'cookies',
      imageUrl: 'assets/images/products/cookies/butter_cookies.jpg',
      tags: {
        'ar': ['بسكويت', 'زبدة'],
        'en': ['Cookies', 'Butter'],
      },
      stock: 250,
      productType: 'ProductType.weight',
      thumbnail: 'assets/images/products/cookies/butter_cookies.jpg',
      salePrice: 1.25,
      productAttributes: ProductAttributeModel(
        name: 'weight',
        values: ['250g', '500g', '1kg'],
      ),
    ),
    ProductModel(
      id: 'cookie_003',
      name: {
        'ar': 'كوكيز الفانيليا',
        'en': 'Vanilla Cookies',
      },
      description: {
        'ar': 'كوكيز فانيليا مع سكر ملون.',
        'en': 'Vanilla cookies with colored sugar.',
      },
      price: 1.50,
      category: 'cookies',
      imageUrl: 'assets/images/products/cookies/vanilla_sugar_cookies.jpg',
      tags: {
        'ar': ['بسكويت', 'فانيليا'],
        'en': ['Cookies', 'Vanilla'],
      },
      stock: 240,
      productType: 'ProductType.weight',
      thumbnail: 'assets/images/products/cookies/vanilla_sugar_cookies.jpg',
      salePrice: 1.25,
      productAttributes: ProductAttributeModel(
        name: 'weight',
        values: ['250g', '500g', '1kg'],
      ),
    ),
    ProductModel(
      id: 'cookie_004',
      name: {
        'ar': 'كوكيز الشوكولاتة بالنعناع',
        'en': 'Mint Chocolate Cookies',
      },
      description: {
        'ar': 'كوكيز شوكولاتة مع نكهة النعناع.',
        'en': 'Chocolate cookies with mint flavor.',
      },
      price: 2.00,
      category: 'cookies',
      imageUrl:
          'assets/images/products/cookies/mint_chocolate_chip_cookies.jpg',
      tags: {
        'ar': ['بسكويت', 'شوكولاتة', 'نعناع'],
        'en': ['Cookies', 'Chocolate', 'Mint'],
      },
      stock: 220,
      productType: 'ProductType.weight',
      thumbnail:
          'assets/images/products/cookies/mint_chocolate_chip_cookies.jpg',
      salePrice: 1.75,
      productAttributes: ProductAttributeModel(
        name: 'weight',
        values: ['250g', '500g', '1kg'],
      ),
    ),
    ProductModel(
      id: 'cookie_005',
      name: {
        'ar': 'كوكيز الجوز',
        'en': 'Walnut Cookies',
      },
      description: {
        'ar': 'كوكيز جوز مع القرفة.',
        'en': 'Walnut cookies with cinnamon.',
      },
      price: 2.00,
      category: 'cookies',
      imageUrl: 'assets/images/products/cookies/cinnamon_walnut_cookies.jpg',
      tags: {
        'ar': ['بسكويت', 'جوز'],
        'en': ['Cookies', 'Walnut'],
      },
      stock: 210,
      productType: 'ProductType.weight',
      thumbnail: 'assets/images/products/cookies/cinnamon_walnut_cookies.jpg',
      salePrice: 1.75,
      productAttributes: ProductAttributeModel(
        name: 'weight',
        values: ['250g', '500g', '1kg'],
      ),
    ),
    ProductModel(
      id: 'cookie_006',
      name: {
        'ar': 'كوكيز الكراميل المملح',
        'en': 'Salted Caramel Cookies',
      },
      description: {
        'ar': 'كوكيز كراميل مع ملح البحر.',
        'en': 'Caramel cookies with sea salt.',
      },
      price: 2.50,
      category: 'cookies',
      imageUrl: 'assets/images/products/cookies/salted_caramel_cookies.jpg',
      tags: {
        'ar': ['بسكويت', 'كراميل'],
        'en': ['Cookies', 'Caramel'],
      },
      stock: 200,
      productType: 'ProductType.weight',
      thumbnail: 'assets/images/products/cookies/salted_caramel_cookies.jpg',
      salePrice: 2.25,
      productAttributes: ProductAttributeModel(
        name: 'weight',
        values: ['250g', '500g', '1kg'],
      ),
    ),
    ProductModel(
      id: 'cookie_007',
      name: {
        'ar': 'كوكيز الشوكولاتة البيضاء',
        'en': 'White Chocolate Cookies',
      },
      description: {
        'ar': 'كوكيز شوكولاتة بيضاء مع التوت.',
        'en': 'White chocolate cookies with raspberries.',
      },
      price: 2.00,
      category: 'cookies',
      imageUrl:
          'assets/images/products/cookies/white_chocolate_raspberry_cookies.jpg',
      tags: {
        'ar': ['بسكويت', 'شوكولاتة بيضاء'],
        'en': ['Cookies', 'White Chocolate'],
      },
      stock: 190,
      productType: 'ProductType.weight',
      thumbnail:
          'assets/images/products/cookies/white_chocolate_raspberry_cookies.jpg',
      salePrice: 1.75,
      productAttributes: ProductAttributeModel(
        name: 'weight',
        values: ['250g', '500g', '1kg'],
      ),
    ),
    ProductModel(
      id: 'cookie_008',
      name: {
        'ar': 'كوكيز اللوز',
        'en': 'Almond Cookies',
      },
      description: {
        'ar': 'كوكيز لوز مع الشوكولاتة.',
        'en': 'Almond cookies with chocolate.',
      },
      price: 2.00,
      category: 'cookies',
      imageUrl: 'assets/images/products/cookies/chocolate_almond_cookies.jpg',
      tags: {
        'ar': ['بسكويت', 'لوز'],
        'en': ['Cookies', 'Almond'],
      },
      stock: 180,
      productType: 'ProductType.weight',
      thumbnail: 'assets/images/products/cookies/chocolate_almond_cookies.jpg',
      salePrice: 1.75,
      productAttributes: ProductAttributeModel(
        name: 'weight',
        values: ['250g', '500g', '1kg'],
      ),
    ),
    ProductModel(
      id: 'cookie_009',
      name: {
        'ar': 'كوكيز جوز الهند',
        'en': 'Coconut Cookies',
      },
      description: {
        'ar': 'كوكيز جوز الهند مع الشوكولاتة.',
        'en': 'Coconut cookies with chocolate.',
      },
      price: 2.00,
      category: 'cookies',
      imageUrl: 'assets/images/products/cookies/chocolate_coconut_cookies.jpg',
      tags: {
        'ar': ['بسكويت', 'جوز الهند'],
        'en': ['Cookies', 'Coconut'],
      },
      stock: 170,
      productType: 'ProductType.weight',
      thumbnail: 'assets/images/products/cookies/chocolate_coconut_cookies.jpg',
      salePrice: 1.75,
      productAttributes: ProductAttributeModel(
        name: 'weight',
        values: ['250g', '500g', '1kg'],
      ),
    ),
    ProductModel(
      id: 'cookie_010',
      name: {
        'ar': 'كوكيز القهوة',
        'en': 'Coffee Cookies',
      },
      description: {
        'ar': 'كوكيز قهوة مع الشوكولاتة.',
        'en': 'Coffee cookies with chocolate.',
      },
      price: 2.50,
      category: 'cookies',
      imageUrl: 'assets/images/products/cookies/coffee_chocolate_cookies.jpg',
      tags: {
        'ar': ['بسكويت', 'قهوة'],
        'en': ['Cookies', 'Coffee'],
      },
      stock: 160,
      productType: 'ProductType.weight',
      thumbnail: 'assets/images/products/cookies/coffee_chocolate_cookies.jpg',
      salePrice: 2.25,
      productAttributes: ProductAttributeModel(
        name: 'weight',
        values: ['250g', '500g', '1kg'],
      ),
    ),

    ///////////////healthy////////////////////
    ProductModel(
      id: 'healthy_001',
      name: {
        'ar': 'كيكة الشوكولاتة الخالية من السكر',
        'en': 'Sugar-Free Chocolate Cake',
      },
      description: {
        'ar': 'كيكة شوكولاتة خالية من السكر مع ستيفيا.',
        'en': 'Sugar-free chocolate cake sweetened with stevia.',
      },
      price: 25.00,
      category: 'healthy',
      imageUrl: 'assets/images/products/healthy/sugar_free_chocolate_cake.jpg',
      tags: {
        'ar': ['صحي', 'شوكولاتة', 'خالي من السكر'],
        'en': ['Healthy', 'Chocolate', 'Sugar-Free'],
      },
      stock: 20,
      productType: 'ProductType.size',
      thumbnail: 'assets/images/products/healthy/sugar_free_chocolate_cake.jpg',
      salePrice: 22.00,
      productAttributes: ProductAttributeModel(
        name: 'Size',
        values: ['Large', 'Medium', 'Small'],
      ),
      productVariations: [
        ProductVariationModel(
          id: '1',
          stock: 5,
          price: 25,
          salePrice: 22,
          attributeValues: {'Size': 'Small'},
        ),
        ProductVariationModel(
          id: '2',
          stock: 10,
          price: 30,
          salePrice: 25,
          attributeValues: {'Size': 'Medium'},
        ),
        ProductVariationModel(
          id: '3',
          stock: 15,
          price: 40,
          salePrice: 35,
          attributeValues: {'Size': 'Large'},
        ),
      ],
    ),
    ProductModel(
      id: 'healthy_002',
      name: {
        'ar': 'كوكيز الشوفان بالعسل',
        'en': 'Oatmeal Honey Cookies',
      },
      description: {
        'ar': 'كوكيز شوفان مع العسل الطبيعي.',
        'en': 'Oatmeal cookies with natural honey.',
      },
      price: 2.50,
      category: 'donuts',
      imageUrl: 'assets/images/products/healthy/oatmeal_honey_cookies.jpg',
      tags: {
        'ar': ['صحي', 'شوفان', 'عسل'],
        'en': ['Healthy', 'Oatmeal', 'Honey'],
      },
      stock: 150,
      productType: 'ProductType.weight',
      thumbnail: 'assets/images/products/healthy/oatmeal_honey_cookies.jpg',
      salePrice: 2.25,
      productAttributes: ProductAttributeModel(
        name: 'weight',
        values: ['250g', '500g', '1kg'],
      ),
    ),
    ProductModel(
      id: 'healthy_003',
      name: {
        'ar': 'تشيز كيك نباتي',
        'en': 'Vegan Cheesecake',
      },
      description: {
        'ar': 'تشيز كيك نباتي بالتوت الطازج.',
        'en': 'Vegan cheesecake with fresh berries.',
      },
      price: 30.00,
      category: 'healthy',
      imageUrl: 'assets/images/products/healthy/vegan_blueberry_cheesecake.jpg',
      tags: {
        'ar': ['صحي', 'تشيز كيك', 'نباتي'],
        'en': ['Healthy', 'Cheesecake', 'Vegan'],
      },
      stock: 15,
      productType: 'ProductType.size',
      thumbnail:
          'assets/images/products/healthy/vegan_blueberry_cheesecake.jpg',
      salePrice: 28.00,
      productAttributes: ProductAttributeModel(
        name: 'Size',
        values: ['Large', 'Medium', 'Small'],
      ),
      productVariations: [
        ProductVariationModel(
          id: '1',
          stock: 5,
          price: 30,
          salePrice: 28,
          attributeValues: {'Size': 'Small'},
        ),
        ProductVariationModel(
          id: '2',
          stock: 10,
          price: 35,
          salePrice: 30,
          attributeValues: {'Size': 'Medium'},
        ),
        ProductVariationModel(
          id: '3',
          stock: 15,
          price: 45,
          salePrice: 40,
          attributeValues: {'Size': 'Large'},
        ),
      ],
    ),
    ProductModel(
      id: 'healthy_004',
      name: {
        'ar': 'بارفيه التوت',
        'en': 'Berry Parfait',
      },
      description: {
        'ar': 'بارفيه التوت مع الزبادي اليوناني.',
        'en': 'Berry parfait with Greek yogurt.',
      },
      price: 15.00,
      category: 'healthy',
      imageUrl:
          'assets/images/products/healthy/blueberry_parfait_with_greek_yogurt.jpg',
      tags: {
        'ar': ['صحي', 'توت', 'زبادي'],
        'en': ['Healthy', 'Berries', 'Yogurt'],
      },
      stock: 50,
      productType: 'ProductType.single',
      thumbnail:
          'assets/images/products/healthy/blueberry_parfait_with_greek_yogurt.jpg',
      salePrice: 13.00,
      productAttributes: ProductAttributeModel(
        name: 'weight',
        values: ['250g', '500g', '1kg'],
      ),
    ),
    ProductModel(
      id: 'healthy_005',
      name: {
        'ar': 'كرات التمر بالمكسرات',
        'en': 'Date Nut Balls',
      },
      description: {
        'ar': 'كرات التمر مع المكسرات وجوز الهند.',
        'en': 'Date balls with nuts and coconut.',
      },
      price: 10.00,
      category: 'healthy',
      imageUrl: 'assets/images/products/healthy/date_nut_balls.jpg',
      tags: {
        'ar': ['صحي', 'تمر', 'مكسرات'],
        'en': ['Healthy', 'Dates', 'Nuts'],
      },
      stock: 100,
      productType: 'ProductType.weight',
      thumbnail: 'assets/images/products/healthy/date_nut_balls.jpg',
      salePrice: 8.00,
      productAttributes: ProductAttributeModel(
        name: 'weight',
        values: ['250g', '500g', '1kg'],
      ),
    ),
    ProductModel(
      id: 'healthy_006',
      name: {
        'ar': 'كيكة الجزر الخالية من الجلوتين',
        'en': 'Gluten-Free Carrot Cake',
      },
      description: {
        'ar': 'كيكة جزر خالية من الجلوتين.',
        'en': 'Gluten-free carrot cake.',
      },
      price: 22.00,
      category: 'healthy',
      imageUrl: 'assets/images/products/healthy/gluten_free_carrot_cake.jpg',
      tags: {
        'ar': ['صحي', 'جزر', 'خالي من الجلوتين'],
        'en': ['Healthy', 'Carrot', 'Gluten-Free'],
      },
      stock: 25,
      productType: 'ProductType.size',
      thumbnail: 'assets/images/products/healthy/gluten_free_carrot_cake.jpg',
      salePrice: 20.00,
      productAttributes: ProductAttributeModel(
        name: 'Size',
        values: ['Large', 'Medium', 'Small'],
      ),
      productVariations: [
        ProductVariationModel(
          id: '1',
          stock: 5,
          price: 22,
          salePrice: 20,
          attributeValues: {'Size': 'Small'},
        ),
        ProductVariationModel(
          id: '2',
          stock: 10,
          price: 28,
          salePrice: 25,
          attributeValues: {'Size': 'Medium'},
        ),
        ProductVariationModel(
          id: '3',
          stock: 15,
          price: 35,
          salePrice: 30,
          attributeValues: {'Size': 'Large'},
        ),
      ],
    ),
    ProductModel(
      id: 'healthy_007',
      name: {
        'ar': 'كوكيز الشوكولاتة الخالية من الدقيق',
        'en': 'Flourless Chocolate Cookies',
      },
      description: {
        'ar': 'كوكيز شوكولاتة خالية من الدقيق.',
        'en': 'Flourless chocolate cookies.',
      },
      price: 2.50,
      category: 'healthy',
      imageUrl:
          'assets/images/products/healthy/flourless_chocolate_cookies.jpg',
      tags: {
        'ar': ['صحي', 'شوكولاتة', 'خالي من الدقيق'],
        'en': ['Healthy', 'Chocolate', 'Flourless'],
      },
      stock: 120,
      productType: 'ProductType.weight',
      thumbnail:
          'assets/images/products/healthy/flourless_chocolate_cookies.jpg',
      salePrice: 2.25,
      productAttributes: ProductAttributeModel(
        name: 'weight',
        values: ['250g', '500g', '1kg'],
      ),
    ),
    ProductModel(
      id: 'healthy_008',
      name: {
        'ar': 'بودنغ الشيا',
        'en': 'Chia Pudding',
      },
      description: {
        'ar': 'بودنغ الشيا مع الفواكه الطازجة.',
        'en': 'Chia pudding with fresh fruits.',
      },
      price: 12.00,
      category: 'healthy',
      imageUrl: 'assets/images/products/healthy/chia_pudding.jpg',
      tags: {
        'ar': ['صحي', 'شيا', 'فواكه'],
        'en': ['Healthy', 'Chia', 'Fruits'],
      },
      stock: 60,
      productType: 'ProductType.single',
      thumbnail: 'assets/images/products/healthy/chia_pudding.jpg',
      salePrice: 10.00,
      productAttributes: ProductAttributeModel(
        name: 'weight',
        values: ['250g', '500g', '1kg'],
      ),
    ),
    ProductModel(
      id: 'healthy_009',
      name: {
        'ar': 'كعكة الشوفان بالموز',
        'en': 'Oatmeal Banana Cake',
      },
      description: {
        'ar': 'كعكة شوفان مع الموز والعسل.',
        'en': 'Oatmeal cake with banana and honey.',
      },
      price: 18.00,
      category: 'healthy',
      imageUrl: 'assets/images/products/healthy/oatmeal_banana_cake.jpg',
      tags: {
        'ar': ['صحي', 'شوفان', 'موز'],
        'en': ['Healthy', 'Oatmeal', 'Banana'],
      },
      stock: 30,
      productType: 'ProductType.weight',
      thumbnail: 'assets/images/products/healthy/oatmeal_banana_cake.jpg',
      salePrice: 16.00,
      productAttributes: ProductAttributeModel(
        name: 'weight',
        values: ['250g', '500g', '1kg'],
      ),
    ),
    ProductModel(
      id: 'healthy_010',
      name: {
        'ar': 'كرات البروتين بالشوكولاتة',
        'en': 'Chocolate Protein Balls',
      },
      description: {
        'ar': 'كرات بروتين مع الشوكولاتة الداكنة.',
        'en': 'Protein balls with dark chocolate.',
      },
      price: 3.00,
      category: 'healthy',
      imageUrl: 'assets/images/products/healthy/chocolate_protein_balls.jpg',
      tags: {
        'ar': ['صحي', 'بروتين', 'شوكولاتة'],
        'en': ['Healthy', 'Protein', 'Chocolate'],
      },
      stock: 200,
      productType: 'ProductType.weight',
      thumbnail: 'assets/images/products/healthy/chocolate_protein_balls.jpg',
      salePrice: 2.75,
      productAttributes: ProductAttributeModel(
        name: 'weight',
        values: ['250g', '500g', '1kg'],
      ),
    ),
  ];
}
