import 'package:cake_and_smile/utils/constants/enums.dart';
import 'package:get/get.dart';

import '../../features/bakery/models/category_model.dart';
import '../../features/bakery/models/product_model.dart';
import '../../features/bakery/models/products_attributes_model.dart';
import '../../features/bakery/models/products_variations_model.dart';

// final ProductModels = <ProductModel>[].obs;
final List<CategoryModels> categoriesDummyData = [
  CategoryModels(
    id: '1',
    name: 'Cakes',
    image: 'assets/images/catgorey_images/Cakes.jpg',
    description: 'استمتع بتشكيلة واسعة من الكيكات الطازجة.',
    isFeatured: false,
  ),
  CategoryModels(
    id: '2',
    name: 'Oriental',
    image: 'assets/images/catgorey_images/OrientalDesserts.jpg',
    description: 'اكتشف مذاق الحلويات الشرقية الأصيلة.',
    isFeatured: false,
  ),
  CategoryModels(
    id: '3',
    name: 'Western',
    image: 'assets/images/catgorey_images/WesternDesserts.jpg',
    description: 'تذوق أفضل الحلويات الغربية.',
    isFeatured: false,
  ),
  CategoryModels(
    id: '4',
    name: 'Donuts',
    image: 'assets/images/catgorey_images/Donuts.jpg',
    description: 'دوناتس طازجة ولذيذة!',
    isFeatured: false,
  ),
  CategoryModels(
    id: '5',
    name: 'Biscuits&Cookies',
    image: 'assets/images/catgorey_images/Biscuits&Cookies.jpg',
    description: 'بسكويت وكوكيز مقرمشة ولذيذة.',
    isFeatured: false,
  ),
  CategoryModels(
    id: '6',
    name: 'Healthy',
    image: 'assets/images/catgorey_images/HealthyDesserts.jpg',
    description: 'حلويات لذيذة وصحية!',
    isFeatured: false,
  )
];

List<ProductModel> initializeDummyData() {
  return [
    // Cake ProductModels
    ProductModel(
      stock: 2,
      id: 'cake_001',
      name: 'الكيكة الفانيليا الكلاسيكية',
      description: 'كيكة فانيليا طرية وناعمة، مغطاة بكريمة زبدة لذيذة وخفيفة.',
      price: 25.00,
      productType: 'ProductType.size',
      thumbnail: 'assets/images/products/cakes/vanilla_cake.jpg',
      salePrice: 20.00,
      category: 'cakes',
      imageUrl: 'assets/images/products/cakes/vanilla_cake.jpg',
      tags: ['كيكات', 'فانيليا', 'صحي'],
      productAttributes: ProductAttributeModel(
        name: 'Size',
        values: ['Large', 'Medium', 'Small'],
      ),
      productVariations: [
        ProductVariationModel(
          id: '1',
          stock: 2,
          price: 10,
          salePrice: 8,
          attributeValues: {'Size': 'Small'},
        ),
        ProductVariationModel(
          id: '2',
          stock: 2,
          price: 10,
          salePrice: 8,
          attributeValues: {'Size': 'Medium'},
        ),
        ProductVariationModel(
          id: '3',
          stock: 2,
          price: 10,
          salePrice: 8,
          attributeValues: {'Size': 'Large'},
        ),
      ],
    ),
    ProductModel(
      stock: 2,
      id: 'cake_002',
      name: 'كيكة الشوكولاتة الكلاسيكية',
      description: 'كيكة شوكولاتة غنية وطرية، مغطاة بصوص الشوكولاتة الساخن.',
      price: 30.00,
      productType: 'ProductType.size',
      thumbnail: 'assets/images/products/cakes/chocolate_cake.jpg',
      salePrice: 20.00,
      category: 'cakes',
      imageUrl: 'assets/images/products/cakes/chocolate_cake.jpg',
      tags: ['كيكات', 'شوكولاتة', 'صحي'],
      productAttributes: ProductAttributeModel(
        name: 'Size',
        values: ['Large', 'Medium', 'Small'],
      ),
      productVariations: [
        ProductVariationModel(
          id: '1',
          stock: 2,
          price: 10,
          salePrice: 8,
          attributeValues: {'Size': 'Small'},
        ),
        ProductVariationModel(
          id: '2',
          stock: 2,
          price: 15,
          salePrice: 10,
          attributeValues: {'Size': 'Medium'},
        ),
        ProductVariationModel(
          id: '3',
          stock: 2,
          price: 20,
          salePrice: 15,
          attributeValues: {'Size': 'Large'},
        ),
      ],
    ),

    ProductModel(
      stock: 2,
      id: 'cake_003',
      name: 'كيكة الجزر',
      description: 'كيكة جزر لذيذة مع جوز الهند، مغطاة بجبنة الكريمة.',
      price: 28.00,
      productType: 'ProductType.size',
      thumbnail: 'assets/images/products/cakes/carrot_cake_1.jpg',
      salePrice: 20.00,
      category: 'cakes',
      imageUrl: 'assets/images/products/cakes/carrot_cake_1.jpg',
      tags: ['كيكات', 'جزر', 'صحي'],
      productAttributes: ProductAttributeModel(
        name: 'Size',
        values: ['Large', 'Medium', 'Small'],
      ),
      productVariations: [
        ProductVariationModel(
          id: '1',
          stock: 5,
          price: 28,
          salePrice: 20,
          attributeValues: {'Size': 'Small'},
        ),
        ProductVariationModel(
          id: '2',
          stock: 3,
          price: 35,
          salePrice: 25,
          attributeValues: {'Size': 'Medium'},
        ),
        ProductVariationModel(
          id: '3',
          stock: 2,
          price: 45,
          salePrice: 30,
          attributeValues: {'Size': 'Large'},
        ),
      ],
    ),
    ProductModel(
      stock: 2,
      id: 'cake_004',
      name: 'كيكة الليمون',
      description: 'كيكة ليمون منعشة مع غلاف سكر ليموني.',
      price: 22.00,
      productType: 'ProductType.size',
      thumbnail: 'assets/images/products/cakes/lemon_cake.jpg',
      salePrice: 20.00,
      category: 'cakes',
      imageUrl: 'assets/images/products/cakes/lemon_cake.jpg',
      tags: ['كيكات', 'ليمون', 'صحي'],
      productAttributes: ProductAttributeModel(
        name: 'Size',
        values: ['Large', 'Medium', 'Small'],
      ),
      productVariations: [
        ProductVariationModel(
          id: '1',
          stock: 4,
          price: 22,
          salePrice: 18,
          attributeValues: {'Size': 'Small'},
        ),
        ProductVariationModel(
          id: '2',
          stock: 3,
          price: 28,
          salePrice: 22,
          attributeValues: {'Size': 'Medium'},
        ),
        ProductVariationModel(
          id: '3',
          stock: 1,
          price: 35,
          salePrice: 28,
          attributeValues: {'Size': 'Large'},
        ),
      ],
    ),
    ProductModel(
      stock: 2,
      id: 'cake_005',
      name: 'كيكة الكراميل المملحة',
      description: 'كيكة كراميل مع طبقة من الكراميل المملح.',
      price: 32.00,
      productType: 'ProductType.size',
      thumbnail: 'assets/images/products/cakes/salted_caramel_cake.jpg',
      salePrice: 20.00,
      category: 'cakes',
      imageUrl: 'assets/images/products/cakes/salted_caramel_cake.jpg',
      tags: ['كيكات', 'كراميل', 'صحي'],
      productAttributes: ProductAttributeModel(
        name: 'Size',
        values: ['Large', 'Medium', 'Small'],
      ),
      productVariations: [
        ProductVariationModel(
          id: '1',
          stock: 6,
          price: 32,
          salePrice: 25,
          attributeValues: {'Size': 'Small'},
        ),
        ProductVariationModel(
          id: '2',
          stock: 4,
          price: 40,
          salePrice: 30,
          attributeValues: {'Size': 'Medium'},
        ),
        ProductVariationModel(
          id: '3',
          stock: 2,
          price: 50,
          salePrice: 35,
          attributeValues: {'Size': 'Large'},
        ),
      ],
    ),
    ProductModel(
      stock: 2,
      id: 'cake_006',
      name: 'كيكة الجبنة بالتوت',
      description: 'تشيز كيك كريمي مع طبقة من التوت الطازج.',
      price: 35.00,
      productType: 'ProductType.size',
      thumbnail: 'assets/images/products/cakes/cheesecake_berries.jpg',
      salePrice: 20.00,
      category: 'cakes',
      imageUrl: 'assets/images/products/cakes/cheesecake_berries.jpg',
      tags: ['كيكات', 'تشيز كيك', 'توت'],
      productAttributes: ProductAttributeModel(
        name: 'Size',
        values: ['Large', 'Medium', 'Small'],
      ),
      productVariations: [
        ProductVariationModel(
          id: '1',
          stock: 7,
          price: 35,
          salePrice: 28,
          attributeValues: {'Size': 'Small'},
        ),
        ProductVariationModel(
          id: '2',
          stock: 5,
          price: 45,
          salePrice: 35,
          attributeValues: {'Size': 'Medium'},
        ),
        ProductVariationModel(
          id: '3',
          stock: 3,
          price: 55,
          salePrice: 40,
          attributeValues: {'Size': 'Large'},
        ),
      ],
    ),
    ProductModel(
      id: 'cake_007',
      name: 'كيكة القهوة',
      description: 'كيكة قهوة مع طبقة من الموكا.',
      price: 27.00,
      category: 'cakes',
      imageUrl: 'assets/images/products/cakes/coffee_cake_1.jpg',
      tags: ['كيكات', 'قهوة', 'صحي'],
      stock: 50,
      productType: 'ProductType.size',
      thumbnail: 'assets/images/products/cakes/coffee_cake_1.jpg',
      salePrice: 24.00,
      productAttributes: ProductAttributeModel(
        name: 'Size',
        values: ['Large', 'Medium', 'Small'],
      ),
      productVariations: [
        ProductVariationModel(
          id: '1',
          stock: 10,
          price: 27,
          salePrice: 22,
          attributeValues: {'Size': 'Small'},
        ),
        ProductVariationModel(
          id: '2',
          stock: 8,
          price: 35,
          salePrice: 28,
          attributeValues: {'Size': 'Medium'},
        ),
        ProductVariationModel(
          id: '3',
          stock: 5,
          price: 45,
          salePrice: 35,
          attributeValues: {'Size': 'Large'},
        ),
      ],
    ),
    ProductModel(
      id: 'cake_008',
      name: 'كيكة الشوكولاتة بالنعناع',
      description: 'كيكة شوكولاتة مع نكهة النعناع المنعشة.',
      price: 29.00,
      category: 'cakes',
      imageUrl: 'assets/images/products/cakes/chocolate_mint_cake.jpg',
      tags: ['كيكات', 'شوكولاتة', 'نعناع'],
      stock: 40,
      productType: 'ProductType.size',
      thumbnail: 'assets/images/products/cakes/chocolate_mint_cake.jpg',
      salePrice: 26.00,
      productAttributes: ProductAttributeModel(
        name: 'Size',
        values: ['Large', 'Medium', 'Small'],
      ),
      productVariations: [
        ProductVariationModel(
          id: '1',
          stock: 12,
          price: 29,
          salePrice: 24,
          attributeValues: {'Size': 'Small'},
        ),
        ProductVariationModel(
          id: '2',
          stock: 10,
          price: 37,
          salePrice: 30,
          attributeValues: {'Size': 'Medium'},
        ),
        ProductVariationModel(
          id: '3',
          stock: 6,
          price: 47,
          salePrice: 37,
          attributeValues: {'Size': 'Large'},
        ),
      ],
    ),
    ProductModel(
      id: 'cake_009',
      name: 'كيكة الفواكه الطازجة',
      description: 'كيكة فواكه طازجة مع كريمة خفيفة.',
      price: 26.00,
      category: 'cakes',
      imageUrl: 'assets/images/products/cakes/fresh_fruit_cake.jpg',
      tags: ['كيكات', 'فواكه', 'صحي'],
      stock: 35,
      productType: 'ProductType.size',
      thumbnail: 'assets/images/products/cakes/fresh_fruit_cake.jpg',
      salePrice: 23.00,
      productAttributes: ProductAttributeModel(
        name: 'Size',
        values: ['Large', 'Medium', 'Small'],
      ),
      productVariations: [
        ProductVariationModel(
          id: '1',
          stock: 15,
          price: 26,
          salePrice: 21,
          attributeValues: {'Size': 'Small'},
        ),
        ProductVariationModel(
          id: '2',
          stock: 12,
          price: 33,
          salePrice: 26,
          attributeValues: {'Size': 'Medium'},
        ),
        ProductVariationModel(
          id: '3',
          stock: 8,
          price: 42,
          salePrice: 33,
          attributeValues: {'Size': 'Large'},
        ),
      ],
    ),
    ProductModel(
      id: 'cake_010',
      name: 'كيكة الكرز الأسود',
      description: 'كيكة شوكولاتة مع طبقة من الكرز الأسود.',
      price: 31.00,
      category: 'cakes',
      imageUrl: 'assets/images/products/cakes/black_forest_cake.jpg',
      tags: ['كيكات', 'شوكولاتة', 'كرز'],
      stock: 30,
      productType: 'ProductType.size',
      thumbnail: 'assets/images/products/cakes/black_forest_cake.jpg',
      salePrice: 28.00,
      productAttributes: ProductAttributeModel(
        name: 'Size',
        values: ['Large', 'Medium', 'Small'],
      ),
      productVariations: [
        ProductVariationModel(
          id: '1',
          stock: 18,
          price: 31,
          salePrice: 25,
          attributeValues: {'Size': 'Small'},
        ),
        ProductVariationModel(
          id: '2',
          stock: 15,
          price: 39,
          salePrice: 31,
          attributeValues: {'Size': 'Medium'},
        ),
        ProductVariationModel(
          id: '3',
          stock: 10,
          price: 49,
          salePrice: 39,
          attributeValues: {'Size': 'Large'},
        ),
      ],
    ),
    /*
     stock,
    ProductModel(
      id: 'oriental_001',
      name: 'الكنافة بالقشطة',
      description: 'كنافة مقرمشة محشوة بالقشطة الطازجة.',
      price: 20.00,
      category: 'oriental',
      imageUrl: 'assets/images/products/oriental/kunafa_cream.jpg',
      tags: ['حلويات شرقية', 'كنافة', 'قشطة'],
      stock: 5,
      productType: 'ProductType.weight',
      thumbnail: 'assets/images/products/oriental/kunafa_cream.jpg',
      salePrice: 18.00,
      productAttributes: ProductAttributeModel(
        name: 'weight',
        values: ['250g', '500g', '1kg'],
      ),
       productVariations: [
        ProductVariationModel(
          id: '1',
          stock: 2,
          price: 10,
          salePrice: 8,
          attributeValues: {'weight': '250g'},
        ),
        ProductVariationModel(
          id: '2',
          stock: 2,
          price: 15,
          salePrice: 10,
          attributeValues: {'weight': '500g'},
        ),
        ProductVariationModel(
          id: '3',
          stock: 2,
          price: 20,
          salePrice: 15,
          attributeValues: {'weight': '1kg'},
        ),
      ],
    ),

     */
    // Oriental Desserts
    ProductModel(
      id: 'oriental_001',
      name: 'الكنافة بالقشطة',
      description: 'كنافة مقرمشة محشوة بالقشطة الطازجة.',
      price: 20.00,
      category: 'oriental',
      imageUrl: 'assets/images/products/oriental/kunafa_cream.jpg',
      tags: ['حلويات شرقية', 'كنافة', 'قشطة'],
      stock: 0.5,
      productType: 'ProductType.weight',
      thumbnail: 'assets/images/products/oriental/kunafa_cream.jpg',
      salePrice: 18.00,
      productAttributes: ProductAttributeModel(
        name: 'weight',
        values: ['250g', '500g', '1kg'],
      ),
    ),
    ProductModel(
        id: 'oriental_002',
        name: 'البقلاوة بالفستق',
        description: 'بقلاوة محشوة بالفستق ومغطاة بالقطر.',
        price: 18.00,
        category: 'oriental',
        imageUrl: 'assets/images/products/oriental/baklava_pistachio.jpg',
        tags: ['حلويات شرقية', 'بقلاوة', 'فستق'],
        stock: 5,
        productType: 'ProductType.weight',
        thumbnail: 'assets/images/products/oriental/baklava_pistachio.jpg',
        salePrice: 16.00,
        productAttributes: ProductAttributeModel(
          name: 'weight',
          values: ['250g', '500g', '1kg'],
        )),
    ProductModel(
        id: 'oriental_003',
        name: 'القطايف بالمكسرات',
        description: 'قطايف محشوة بالمكسرات ومقلية.',
        price: 15.00,
        category: 'oriental',
        imageUrl: 'assets/images/products/oriental/katayef_nuts.jpg',
        tags: ['حلويات شرقية', 'قطايف', 'مكسرات'],
        stock: 70,
        productType: 'ProductType.weight',
        thumbnail: 'assets/images/products/oriental/katayef_nuts.jpg',
        salePrice: 13.00,
        productAttributes: ProductAttributeModel(
          name: 'weight',
          values: ['250g', '500g', '1kg'],
        )),
    ProductModel(
        id: 'oriental_004',
        name: 'البسبوسة بجوز الهند',
        description: 'بسبوسة ناعمة مع جوز الهند وقطر لذيذ.',
        price: 12.00,
        category: 'oriental',
        imageUrl: 'assets/images/products/oriental/basbousa.jpg',
        tags: ['حلويات شرقية', 'بسبوسة', 'جوز الهند'],
        stock: 65,
        productType: 'ProductType.weight',
        thumbnail: 'assets/images/products/oriental/basbousa.jpg',
        salePrice: 10.00,
        productAttributes: ProductAttributeModel(
          name: 'weight',
          values: ['250g', '500g', '1kg'],
        )),
    ProductModel(
        id: 'oriental_005',
        name: 'أم علي',
        description: 'أم علي بالقشطة والمكسرات والزبيب.',
        price: 16.00,
        category: 'oriental',
        imageUrl: 'assets/images/products/oriental/um_ali.jpg',
        tags: ['حلويات شرقية', 'أم علي', 'قشطة'],
        stock: 50,
        productType: 'ProductType.weight',
        thumbnail: 'assets/images/products/oriental/um_ali.jpg',
        salePrice: 14.00,
        productAttributes: ProductAttributeModel(
          name: 'weight',
          values: ['250g', '500g', '1kg'],
        )),
    ProductModel(
        id: 'oriental_006',
        name: 'المهلبيّة بالفستق',
        description: 'مهلبيّة كريمية مع طبقة من الفستق.',
        price: 14.00,
        category: 'oriental',
        imageUrl: 'assets/images/products/oriental/muhalabia_pistachio.jpg',
        tags: ['حلويات شرقية', 'مهلبيّة', 'فستق'],
        stock: 45,
        productType: 'ProductType.weight',
        thumbnail: 'assets/images/products/oriental/muhalabia_pistachio.jpg',
        salePrice: 12.00,
        productAttributes: ProductAttributeModel(
          name: 'weight',
          values: ['250g', '500g', '1kg'],
        )),
    ProductModel(
        id: 'oriental_007',
        name: 'اللقيمات',
        description:
            'لقيمات مقرمشة من الخارج وطرية من الداخل، تقدم مع القطر أو العسل.',
        price: 10.00,
        category: 'oriental',
        imageUrl: 'assets/images/products/oriental/zalabia.jpg',
        tags: ['حلويات شرقية', 'لقيمات', 'عسل'],
        stock: 80,
        productType: 'ProductType.weight',
        thumbnail: 'assets/images/products/oriental/zalabia.jpg',
        salePrice: 8.00,
        productAttributes: ProductAttributeModel(
          name: 'weight',
          values: ['250g', '500g', '1kg'],
        )),
    ProductModel(
        id: 'oriental_008',
        name: 'الغريبة بالسميد',
        description: 'غريبة ناعمة ومقرمشة مصنوعة من السميد.',
        price: 8.00,
        category: 'oriental',
        imageUrl: 'assets/images/products/oriental/ghraybeh.jpg',
        tags: ['حلويات شرقية', 'غريبة', 'سميد'],
        stock: 75,
        productType: 'ProductType.weight',
        thumbnail: 'assets/images/products/oriental/ghraybeh.jpg',
        salePrice: 6.00,
        productAttributes: ProductAttributeModel(
          name: 'weight',
          values: ['250g', '500g', '1kg'],
        )),
    ProductModel(
        id: 'oriental_009',
        name: 'الكنافة النابلسية',
        description: 'كنافة نابلسية مقرمشة مع الجبنة.',
        price: 22.00,
        category: 'oriental',
        imageUrl: 'assets/images/products/oriental/kunafa_cream.jpg',
        tags: ['حلويات شرقية', 'كنافة', 'جبنة'],
        stock: 40,
        productType: 'ProductType.weight',
        thumbnail: 'assets/images/products/oriental/kunafa_cream.jpg',
        salePrice: 20.00,
        productAttributes: ProductAttributeModel(
          name: 'weight',
          values: ['250g', '500g', '1kg'],
        )),
    ProductModel(
        id: 'oriental_010',
        name: 'المعمول بالتمر',
        description: 'معمول محشو بالتمر ومغطى بالسكر البودرة.',
        price: 12.00,
        category: 'oriental',
        imageUrl: 'assets/images/products/oriental/maamoul.jpg',
        tags: ['حلويات شرقية', 'معمول', 'تمر'],
        stock: 60,
        productType: 'ProductType.weight',
        thumbnail: 'assets/images/products/oriental/maamoul.jpg',
        salePrice: 10.00,
        productAttributes: ProductAttributeModel(
          name: 'weight',
          values: ['250g', '500g', '1kg'],
        )),

    // Western Desserts
    ProductModel(
      id: 'western_002',
      name: 'تيراميسو الإيطالي',
      description: 'تيراميسو كلاسيكي مع القهوة والكاكاو.',
      price: 28.00,
      category: 'western',
      imageUrl: 'assets/images/products/western/Italian_tiramisu.jpg',
      tags: ['حلويات غربية', 'تيراميسو', 'قهوة'],
      stock: 25,
      productType: 'western',
      thumbnail: 'assets/images/products/western/Italian_tiramisu.jpg',
      salePrice: 25.00,
    ),
    ProductModel(
      id: 'western_003',
      name: 'كب كيك بالشوكولاتة',
      description: 'كب كيك شوكولاتة مع كريمة زبدة.',
      price: 5.00,
      category: 'western',
      imageUrl: 'assets/images/products/western/chocolate_cupcakes.jpg',
      tags: ['حلويات غربية', 'كب كيك', 'شوكولاتة'],
      stock: 100,
      productType: 'western',
      thumbnail: 'assets/images/products/western/chocolate_cupcakes.jpg',
      salePrice: 4.00,
    ),
    ProductModel(
      id: 'western_005',
      name: 'فطيرة التفاح',
      description: 'فطيرة تفاح بالقرفة والسكر البني.',
      price: 22.00,
      category: 'western',
      imageUrl: 'assets/images/products/western/apple_pie.jpg',
      tags: ['حلويات غربية', 'فطيرة', 'تفاح'],
      stock: 30,
      productType: 'western',
      thumbnail: 'assets/images/products/western/apple_pie.jpg',
      salePrice: 20.00,
    ),
    ProductModel(
      id: 'western_006',
      name: 'كعكة الرغيف بالشوكولاتة',
      description: 'كعكة رغيف شوكولاتة طرية.',
      price: 18.00,
      category: 'western',
      imageUrl: 'assets/images/products/western/chocolate_loaf_cake.jpg',
      tags: ['حلويات غربية', 'كعكة', 'شوكولاتة'],
      stock: 35,
      productType: 'western',
      thumbnail: 'assets/images/products/western/chocolate_loaf_cake.jpg',
      salePrice: 16.00,
    ),
    ProductModel(
      id: 'western_008',
      name: 'كعكة الموز مع الجوز',
      description: 'كعكة موز مع قطع الجوز.',
      price: 20.00,
      category: 'western',
      imageUrl: 'assets/images/products/western/banana_cake_with_walnuts.jpg',
      tags: ['حلويات غربية', 'كعكة', 'موز'],
      stock: 40,
      productType: 'western',
      thumbnail: 'assets/images/products/western/banana_cake_with_walnuts.jpg',
      salePrice: 18.00,
    ),
    ProductModel(
      id: 'western_009',
      name: 'كعكة الفانيليا مع الكراميل',
      description: 'كعكة فانيليا مع طبقة من الكراميل.',
      price: 24.00,
      category: 'western',
      imageUrl: 'assets/images/products/western/vanilla_caramel_cake.jpg',
      tags: ['حلويات غربية', 'كعكة', 'فانيليا'],
      stock: 30,
      productType: 'western',
      thumbnail: 'assets/images/products/western/vanilla_caramel_cake.jpg',
      salePrice: 22.00,
    ),

    // Donuts
    ProductModel(
      id: 'donut_001',
      name: 'دوناتس الشوكولاتة',
      description: 'دوناتس مغطاة بصوص الشوكولاتة الغنية.',
      price: 3.00,
      category: 'ProductType.single',
      imageUrl: 'assets/images/products/donuts/chocolate_donuts.jpg',
      tags: ['دوناتس', 'شوكولاتة'],
      stock: 200,
      productType: 'ProductType.single',
      thumbnail: 'assets/images/products/donuts/chocolate_donuts.jpg',
      salePrice: 2.50,
    ),
    ProductModel(
      id: 'donut_002',
      name: 'دوناتس الفانيليا',
      description: 'دوناتس مغطاة بصوص الفانيليا والسبرينكلز.',
      price: 3.00,
      category: 'ProductType.single',
      imageUrl: 'assets/images/products/donuts/vanilla_donuts.jpg',
      tags: ['دوناتس', 'فانيليا'],
      stock: 180,
      productType: 'ProductType.single',
      thumbnail: 'assets/images/products/donuts/vanilla_donuts.jpg',
      salePrice: 2.50,
    ),
    ProductModel(
      id: 'donut_003',
      name: 'دوناتس الكراميل المملح',
      description: 'دوناتس مغطاة بصوص الكراميل المملح.',
      price: 3.50,
      category: 'ProductType.single',
      imageUrl: 'assets/images/products/donuts/salted_caramel_donuts.jpg',
      tags: ['دوناتس', 'كراميل'],
      stock: 150,
      productType: 'ProductType.single',
      thumbnail: 'assets/images/products/donuts/salted_caramel_donuts.jpg',
      salePrice: 3.00,
    ),
    ProductModel(
      id: 'donut_004',
      name: 'دوناتس الفراولة',
      description: 'دوناتس مغطاة بصوص الفراولة والكريمة.',
      price: 3.50,
      category: 'ProductType.single',
      imageUrl: 'assets/images/products/donuts/strawberry_donuts.jpg',
      tags: ['دوناتس', 'فراولة'],
      stock: 160,
      productType: 'ProductType.single',
      thumbnail: 'assets/images/products/donuts/strawberry_donuts.jpg',
      salePrice: 3.00,
    ),
    ProductModel(
      id: 'donut_005',
      name: 'دوناتس الموز',
      description: 'دوناتس بنكهة الموز مع شوكولاتة.',
      price: 3.00,
      category: 'ProductType.single',
      imageUrl: 'assets/images/products/donuts/banana_donuts.jpg',
      tags: ['دوناتس', 'موز'],
      stock: 170,
      productType: 'ProductType.single',
      thumbnail: 'assets/images/products/donuts/banana_donuts.jpg',
      salePrice: 2.50,
    ),
    ProductModel(
      id: 'donut_006',
      name: 'دوناتس القهوة',
      description: 'دوناتس بنكهة القهوة مع الموكا.',
      price: 3.50,
      category: 'ProductType.single',
      imageUrl: 'assets/images/products/donuts/coffee_donuts.jpg',
      tags: ['دوناتس', 'قهوة'],
      stock: 140,
      productType: 'ProductType.single',
      thumbnail: 'assets/images/products/donuts/coffee_donuts.jpg',
      salePrice: 3.00,
    ),
    ProductModel(
      id: 'donut_008',
      name: 'دوناتس الفستق',
      description: 'دوناتس مغطاة بالفستق والشوكولاتة.',
      price: 4.00,
      category: 'ProductType.single',
      imageUrl: 'assets/images/products/donuts/pistachio_donuts.jpg',
      tags: ['دوناتس', 'فستق'],
      stock: 120,
      productType: 'ProductType.single',
      thumbnail: 'assets/images/products/donuts/pistachio_donuts.jpg',
      salePrice: 3.50,
    ),
    ProductModel(
      id: 'donut_009',
      name: 'دوناتس اللوتس',
      description: 'دوناتس مغطاة بصوص اللوتس والكراميل.',
      price: 3.50,
      category: 'ProductType.single',
      imageUrl: 'assets/images/products/donuts/lotus_donuts_with_caramel.jpg',
      tags: ['دوناتس', 'لوتس'],
      stock: 130,
      productType: 'ProductType.single',
      thumbnail: 'assets/images/products/donuts/lotus_donuts_with_caramel.jpg',
      salePrice: 3.00,
    ),
    ProductModel(
      id: 'donut_010',
      name: 'دوناتس الشوكولاتة البيضاء',
      description: 'دوناتس مغطاة بصوص الشوكولاتة البيضاء.',
      price: 3.50,
      category: 'ProductType.single',
      imageUrl: 'assets/images/products/donuts/white_chocolate_donuts.jpg',
      tags: ['دوناتس', 'شوكولاتة بيضاء'],
      stock: 110,
      productType: 'ProductType.single',
      thumbnail: 'assets/images/products/donuts/white_chocolate_donuts.jpg',
      salePrice: 3.00,
    ),

    // Biscuits & Cookies
    ProductModel(
      id: 'cookie_001',
      name: 'كوكيز الشوكولاتة',
      description: 'كوكيز شوكولاتة طرية مع قطع شوكولاتة.',
      price: 2.00,
      category: 'cookies',
      imageUrl:
          'assets/images/products/cookies/oatmeal_chocolate_chip_cookies.jpg',
      tags: ['بسكويت', 'شوكولاتة'],
      stock: 300,
      productType: 'cookie',
      thumbnail:
          'assets/images/products/cookies/oatmeal_chocolate_chip_cookies.jpg',
      salePrice: 1.75,
    ),
    ProductModel(
      id: 'cookie_002',
      name: 'كوكيز الزبدة',
      description: 'كوكيز زبدة كلاسيكية مع سكر.',
      price: 1.50,
      category: 'cookies',
      imageUrl: 'assets/images/products/cookies/butter_cookies.jpg',
      tags: ['بسكويت', 'زبدة'],
      stock: 250,
      productType: 'cookie',
      thumbnail: 'assets/images/products/cookies/butter_cookies.jpg',
      salePrice: 1.25,
    ),
    ProductModel(
      id: 'cookie_003',
      name: 'كوكيز الفانيليا',
      description: 'كوكيز فانيليا مع سكر ملون.',
      price: 1.50,
      category: 'cookies',
      imageUrl: 'assets/images/products/cookies/vanilla_sugar_cookies.jpg',
      tags: ['بسكويت', 'فانيليا'],
      stock: 240,
      productType: 'cookie',
      thumbnail: 'assets/images/products/cookies/vanilla_sugar_cookies.jpg',
      salePrice: 1.25,
    ),
    ProductModel(
      id: 'cookie_004',
      name: 'كوكيز الشوكولاتة بالنعناع',
      description: 'كوكيز شوكولاتة مع نكهة النعناع.',
      price: 2.00,
      category: 'cookies',
      imageUrl:
          'assets/images/products/cookies/mint_chocolate_chip_cookies.jpg',
      tags: ['بسكويت', 'شوكولاتة', 'نعناع'],
      stock: 220,
      productType: 'cookie',
      thumbnail:
          'assets/images/products/cookies/mint_chocolate_chip_cookies.jpg',
      salePrice: 1.75,
    ),
    ProductModel(
      id: 'cookie_005',
      name: 'كوكيز الجوز',
      description: 'كوكيز جوز مع القرفة.',
      price: 2.00,
      category: 'cookies',
      imageUrl: 'assets/images/products/cookies/cinnamon_walnut_cookies.jpg',
      tags: ['بسكويت', 'جوز'],
      stock: 210,
      productType: 'cookie',
      thumbnail: 'assets/images/products/cookies/cinnamon_walnut_cookies.jpg',
      salePrice: 1.75,
    ),
    ProductModel(
      id: 'cookie_006',
      name: 'كوكيز الكراميل المملح',
      description: 'كوكيز كراميل مع ملح البحر.',
      price: 2.50,
      category: 'cookies',
      imageUrl: 'assets/images/products/cookies/salted_caramel_cookies.jpg',
      tags: ['بسكويت', 'كراميل'],
      stock: 200,
      productType: 'cookie',
      thumbnail: 'assets/images/products/cookies/salted_caramel_cookies.jpg',
      salePrice: 2.25,
    ),
    ProductModel(
      id: 'cookie_007',
      name: 'كوكيز الشوكولاتة البيضاء',
      description: 'كوكيز شوكولاتة بيضاء مع التوت.',
      price: 2.00,
      category: 'cookies',
      imageUrl:
          'assets/images/products/cookies/white_chocolate_raspberry_cookies.jpg',
      tags: ['بسكويت', 'شوكولاتة بيضاء'],
      stock: 190,
      productType: 'cookie',
      thumbnail:
          'assets/images/products/cookies/white_chocolate_raspberry_cookies.jpg',
      salePrice: 1.75,
    ),
    ProductModel(
      id: 'cookie_008',
      name: 'كوكيز اللوز',
      description: 'كوكيز لوز مع الشوكولاتة.',
      price: 2.00,
      category: 'cookies',
      imageUrl: 'assets/images/products/cookies/chocolate_almond_cookies.jpg',
      tags: ['بسكويت', 'لوز'],
      stock: 180,
      productType: 'cookie',
      thumbnail: 'assets/images/products/cookies/chocolate_almond_cookies.jpg',
      salePrice: 1.75,
    ),
    ProductModel(
      id: 'cookie_009',
      name: 'كوكيز جوز الهند',
      description: 'كوكيز جوز الهند مع الشوكولاتة.',
      price: 2.00,
      category: 'cookies',
      imageUrl: 'assets/images/products/cookies/chocolate_coconut_cookies.jpg',
      tags: ['بسكويت', 'جوز الهند'],
      stock: 170,
      productType: 'cookie',
      thumbnail: 'assets/images/products/cookies/chocolate_coconut_cookies.jpg',
      salePrice: 1.75,
    ),
    ProductModel(
      id: 'cookie_010',
      name: 'كوكيز القهوة',
      description: 'كوكيز قهوة مع الشوكولاتة.',
      price: 2.50,
      category: 'cookies',
      imageUrl: 'assets/images/products/cookies/coffee_chocolate_cookies.jpg',
      tags: ['بسكويت', 'قهوة'],
      stock: 160,
      productType: 'cookie',
      thumbnail: 'assets/images/products/cookies/coffee_chocolate_cookies.jpg',
      salePrice: 2.25,
    ),

    // Healthy Desserts
    ProductModel(
      id: 'healthy_001',
      name: 'كيكة الشوكولاتة الخالية من السكر',
      description: 'كيكة شوكولاتة خالية من السكر مع ستيفيا.',
      price: 25.00,
      category: 'healthy',
      imageUrl: 'assets/images/products/healthy/sugar_free_chocolate_cake.jpg',
      tags: ['صحي', 'شوكولاتة', 'خالي من السكر'],
      stock: 20,
      productType: 'healthy',
      thumbnail: 'assets/images/products/healthy/sugar_free_chocolate_cake.jpg',
      salePrice: 22.00,
    ),
    ProductModel(
      id: 'healthy_002',
      name: 'كوكيز الشوفان بالعسل',
      description: 'كوكيز شوفان مع العسل الطبيعي.',
      price: 2.50,
      category: 'healthy',
      imageUrl: 'assets/images/products/healthy/oatmeal_honey_cookies.jpg',
      tags: ['صحي', 'شوفان', 'عسل'],
      stock: 150,
      productType: 'healthy',
      thumbnail: 'assets/images/products/healthy/oatmeal_honey_cookies.jpg',
      salePrice: 2.25,
    ),
    ProductModel(
      id: 'healthy_003',
      name: 'تشيز كيك نباتي',
      description: 'تشيز كيك نباتي بالتوت الطازج.',
      price: 30.00,
      category: 'healthy',
      imageUrl: 'assets/images/products/healthy/vegan_blueberry_cheesecake.jpg',
      tags: ['صحي', 'تشيز كيك', 'نباتي'],
      stock: 15,
      productType: 'healthy',
      thumbnail:
          'assets/images/products/healthy/vegan_blueberry_cheesecake.jpg',
      salePrice: 28.00,
    ),
    ProductModel(
      id: 'healthy_004',
      name: 'بارفيه التوت',
      description: 'بارفيه التوت مع الزبادي اليوناني.',
      price: 15.00,
      category: 'healthy',
      imageUrl:
          'assets/images/products/healthy/blueberry_parfait_with_greek_yogurt.jpg',
      tags: ['صحي', 'توت', 'زبادي'],
      stock: 50,
      productType: 'healthy',
      thumbnail:
          'assets/images/products/healthy/blueberry_parfait_with_greek_yogurt.jpg',
      salePrice: 13.00,
    ),
    ProductModel(
      id: 'healthy_005',
      name: 'كرات التمر بالمكسرات',
      description: 'كرات التمر مع المكسرات وجوز الهند.',
      price: 10.00,
      category: 'healthy',
      imageUrl: 'assets/images/products/healthy/date_nut_balls.jpg',
      tags: ['صحي', 'تمر', 'مكسرات'],
      stock: 100,
      productType: 'healthy',
      thumbnail: 'assets/images/products/healthy/date_nut_balls.jpg',
      salePrice: 8.00,
    ),
    ProductModel(
      id: 'healthy_006',
      name: 'كيكة الجزر الخالية من الجلوتين',
      description: 'كيكة جزر خالية من الجلوتين.',
      price: 22.00,
      category: 'healthy',
      imageUrl: 'assets/images/products/healthy/gluten_free_carrot_cake.jpg',
      tags: ['صحي', 'جزر', 'خالي من الجلوتين'],
      stock: 25,
      productType: 'healthy',
      thumbnail: 'assets/images/products/healthy/gluten_free_carrot_cake.jpg',
      salePrice: 20.00,
    ),
    ProductModel(
      id: 'healthy_007',
      name: 'كوكيز الشوكولاتة الخالية من الدقيق',
      description: 'كوكيز شوكولاتة خالية من الدقيق.',
      price: 2.50,
      category: 'healthy',
      imageUrl:
          'assets/images/products/healthy/flourless_chocolate_cookies.jpg',
      tags: ['صحي', 'شوكولاتة', 'خالي من الدقيق'],
      stock: 120,
      productType: 'healthy',
      thumbnail:
          'assets/images/products/healthy/flourless_chocolate_cookies.jpg',
      salePrice: 2.25,
    ),
    ProductModel(
      id: 'healthy_008',
      name: 'بودنغ الشيا',
      description: 'بودنغ الشيا مع الفواكه الطازجة.',
      price: 12.00,
      category: 'healthy',
      imageUrl: 'assets/images/products/healthy/chia_pudding.jpg',
      tags: ['صحي', 'شيا', 'فواكه'],
      stock: 60,
      productType: 'healthy',
      thumbnail: 'assets/images/products/healthy/chia_pudding.jpg',
      salePrice: 10.00,
    ),
    ProductModel(
      id: 'healthy_009',
      name: 'كعكة الشوفان بالموز',
      description: 'كعكة شوفان مع الموز والعسل.',
      price: 18.00,
      category: 'healthy',
      imageUrl: 'assets/images/products/healthy/oatmeal_banana_cake.jpg',
      tags: ['صحي', 'شوفان', 'موز'],
      stock: 30,
      productType: 'healthy',
      thumbnail: 'assets/images/products/healthy/oatmeal_banana_cake.jpg',
      salePrice: 16.00,
    ),
    ProductModel(
      id: 'healthy_010',
      name: 'كرات البروتين بالشوكولاتة',
      description: 'كرات بروتين مع الشوكولاتة الداكنة.',
      price: 3.00,
      category: 'healthy',
      imageUrl: 'assets/images/products/healthy/chocolate_protein_balls.jpg',
      tags: ['صحي', 'بروتين', 'شوكولاتة'],
      stock: 200,
      productType: 'healthy',
      thumbnail: 'assets/images/products/healthy/chocolate_protein_balls.jpg',
      salePrice: 2.75,
    ),
  ];
}















//     List<ProductModel> initializeDummyData() {
//     return [
//       // Cake ProductModels

//       ProductModel(
//         id: 'cake_001',
//         name: 'الكيكة الفانيليا الكلاسيكية',
//         description:
//             'كيكة فانيليا طرية وناعمة، مغطاة بكريمة زبدة لذيذة وخفيفة.',
//         price: 25.00,
//         category: 'cakes',
//         imageUrl: 'assets/images/ProductModels/cakes/vanilla_cake.jpg',
//       ),
//       ProductModel(
//         id: 'cake_002',
//         name: 'كيكة الشوكولاتة الكلاسيكية',
//         description: 'كيكة شوكولاتة غنية وطرية، مغطاة بصوص الشوكولاتة الساخن.',
//         price: 30.00,
//         category: 'cakes_category',
//         imageUrl: 'assets/images/ProductModels/cakes/chocolate_cake.jpg',
//       ),
//       ProductModel(
//         id: 'cake_003',
//         name: 'كيكة الجزر',
//         description: 'كيكة جزر لذيذة مع جوز الهند، مغطاة بجبنة الكريمة.',
//         price: 28.00,
//         category: 'cakes_category',
//         imageUrl: 'assets/images/ProductModels/cakes/carrot_cake_1.jpg',
//       ),
//       ProductModel(
//         id: 'cake_004',
//         name: 'كيكة الليمون',
//         description: 'كيكة ليمون منعشة مع غلاف سكر ليموني.',
//         price: 22.00,
//         category: 'cakes_category',
//         imageUrl: 'assets/images/ProductModels/cakes/lemon_cake.jpg',
//       ),
//       ProductModel(
//         id: 'cake_005',
//         name: 'كيكة الكراميل المملحة',
//         description: 'كيكة كراميل مع طبقة من الكراميل المملح.',
//         price: 32.00,
//         category: 'cakes_category',
//         imageUrl: 'assets/images/ProductModels/cakes/salted_caramel_cake.jpg',
//       ),
//       ProductModel(
//         id: 'cake_006',
//         name: 'كيكة الجبنة بالتوت',
//         description: 'تشيز كيك كريمي مع طبقة من التوت الطازج.',
//         price: 35.00,
//         category: 'cakes_category',
//         imageUrl: 'assets/images/ProductModels/cakes/cheesecake_berries.jpg',
//       ),
//       ProductModel(
//         id: 'cake_007',
//         name: 'كيكة القهوة',
//         description: 'كيكة قهوة مع طبقة من الموكا.',
//         price: 27.00,
//         category: 'cakes_category',
//         imageUrl: 'assets/images/ProductModels/cakes/coffee_cake_1.jpg',
//       ),
//       ProductModel(
//         id: 'cake_008',
//         name: 'كيكة الشوكولاتة بالنعناع',
//         description: 'كيكة شوكولاتة مع نكهة النعناع المنعشة.',
//         price: 29.00,
//         category: 'cakes_category',
//         imageUrl: 'assets/images/ProductModels/cakes/chocolate_mint_cake.jpg',
//       ),
//       ProductModel(
//         id: 'cake_009',
//         name: 'كيكة الفواكه الطازجة',
//         description: 'كيكة فواكه طازجة مع كريمة خفيفة.',
//         price: 26.00,
//         category: 'cakes_category',
//         imageUrl: 'assets/images/ProductModels/cakes/fresh_fruit_cake.jpg',
//       ),
//       ProductModel(
//         id: 'cake_010',
//         name: 'كيكة الكرز الأسود',
//         description: 'كيكة شوكولاتة مع طبقة من الكرز الأسود.',
//         price: 31.00,
//         category: 'cakes_category',
//         imageUrl: 'assets/images/ProductModels/cakes/black_forest_cake.jpg',
//       ),
//       //========================//

//       // Oriental Desserts
//       ProductModel(
//         id: 'oriental_001',
//         name: 'الكنافة بالقشطة',
//         description: 'كنافة مقرمشة محشوة بالقشطة الطازجة.',
//         price: 20.00,
//         category: 'oriental_category',
//         imageUrl: 'assets/images/ProductModels/oriental/kunafa_cream.jpg',
//       ),
//       ProductModel(
//         id: 'oriental_002',
//         name: 'البقلاوة بالفستق',
//         description: 'بقلاوة محشوة بالفستق ومغطاة بالقطر.',
//         price: 18.00,
//         category: 'oriental_category',
//         imageUrl: 'assets/images/ProductModels/oriental/baklava_pistachio.jpg',
//       ),
//       ProductModel(
//         id: 'oriental_003',
//         name: 'القطايف بالمكسرات',
//         description: 'قطايف محشوة بالمكسرات ومقلية.',
//         price: 15.00,
//         category: 'oriental_category',
//         imageUrl: 'assets/images/ProductModels/oriental/katayef_nuts.jpg',
//       ),
//       ProductModel(
//         id: 'oriental_004',
//         name: 'البسبوسة بجوز الهند',
//         description: 'بسبوسة ناعمة مع جوز الهند وقطر لذيذ.',
//         price: 12.00,
//         category: 'oriental_category',
//         imageUrl: 'assets/images/ProductModels/oriental/basbousa.jpg',
//       ),
//       ProductModel(
//         id: 'oriental_005',
//         name: 'أم علي',
//         description: 'أم علي بالقشطة والمكسرات والزبيب.',
//         price: 16.00,
//         category: 'oriental_category',
//         imageUrl: 'assets/images/ProductModels/oriental/um_ali.jpg',
//       ),
//       ProductModel(
//         id: 'oriental_006',
//         name: 'المهلبيّة بالفستق',
//         description: 'مهلبيّة كريمية مع طبقة من الفستق.',
//         price: 14.00,
//         category: 'oriental_category',
//         imageUrl: 'assets/images/ProductModels/oriental/muhalabia_pistachio.jpg',
//       ),
//       ProductModel(
//         id: 'oriental_007',
//         name: 'اللقيمات',
//         description:
//             'لقيمات مقرمشة من الخارج وطرية من الداخل، تقدم مع القطر أو العسل.',
//         price: 10.00,
//         category: 'oriental_category',
//         imageUrl: 'assets/images/ProductModels/oriental/zalabia.jpg',
//       ),
//       ProductModel(
//         id: 'oriental_008',
//         name: 'الغريبة بالسميد',
//         description: 'غريبة ناعمة ومقرمشة مصنوعة من السميد.',
//         price: 8.00,
//         category: 'oriental_category',
//         imageUrl: 'assets/images/ProductModels/oriental/ghraybeh.jpg',
//       ),
//       ProductModel(
//         id: 'oriental_009',
//         name: 'الكنافة النابلسية',
//         description: 'كنافة نابلسية مقرمشة مع الجبنة.',
//         price: 22.00,
//         category: 'oriental_category',
//         imageUrl: 'assets/images/ProductModels/oriental/kunafa_cream.jpg',
//       ),
//       ProductModel(
//         id: 'oriental_010',
//         name: 'المعمول بالتمر',
//         description: 'معمول محشو بالتمر ومغطى بالسكر البودرة.',
//         price: 12.00,
//         category: 'oriental_category',
//         imageUrl: 'assets/images/ProductModels/oriental/maamoul.jpg',
//       ),

//       //========================//
//       // Western Desserts
//       // ProductModel(
//       //   id: 'western_001',
//       //   name: 'تشيز كيك بالتوت',
//       //   description: 'تشيز كيك كريمي مع طبقة من التوت الطازج.',
//       //   price: 35.00,
//       //   category: 'western_category',
//       //   imageUrl: 'assets/images/ProductModels/western/cheesecake_berries.jpg',
//       // ),
//       ProductModel(
//         id: 'western_002',
//         name: 'تيراميسو الإيطالي',
//         description: 'تيراميسو كلاسيكي مع القهوة والكاكاو.',
//         price: 28.00,
//         category: 'western_category',
//         imageUrl: 'assets/images/ProductModels/western/Italian_tiramisu.jpg',
//       ),
//       ProductModel(
//         id: 'western_003',
//         name: 'كب كيك بالشوكولاتة',
//         description: 'كب كيك شوكولاتة مع كريمة زبدة.',
//         price: 5.00,
//         category: 'western_category',
//         imageUrl: 'assets/images/ProductModels/western/chocolate_cupcakes.jpg',
//       ),
//       // ProductModel(
//       //   id: 'western_004',
//       //   name: 'كريب بالفواكه',
//       //   description: 'كريب مع الفواكه الطازجة والكريمة.',
//       //   price: 15.00,
//       //   category: 'western_category',
//       //   imageUrl: 'assets/images/ProductModels/western/fruit_crepe.jpg',
//       // ),
//       ProductModel(
//         id: 'western_005',
//         name: 'فطيرة التفاح',
//         description: 'فطيرة تفاح بالقرفة والسكر البني.',
//         price: 22.00,
//         category: 'western_category',
//         imageUrl: 'assets/images/ProductModels/western/apple_pie.jpg',
//       ),
//       ProductModel(
//         id: 'western_006',
//         name: 'كعكة الرغيف بالشوكولاتة',
//         description: 'كعكة رغيف شوكولاتة طرية.',
//         price: 18.00,
//         category: 'western_category',
//         imageUrl: 'assets/images/ProductModels/western/chocolate_loaf_cake.jpg',
//       ),
//       // ProductModel(
//       //   id: 'western_007',
//       //   name: 'كعكة الجبنة بالفراولة',
//       //   description: 'كعكة جبنة مع طبقة من الفراولة الطازجة.',
//       //   price: 25.00,
//       //   category: 'western_category',
//       //   imageUrl: 'assets/images/ProductModels/western/strawberry_cheesecake.jpg',
//       // ),
//       ProductModel(
//         id: 'western_008',
//         name: 'كعكة الموز مع الجوز',
//         description: 'كعكة موز مع قطع الجوز.',
//         price: 20.00,
//         category: 'western_category',
//         imageUrl: 'assets/images/ProductModels/western/banana_cake_with_walnuts.jpg',
//       ),
//       ProductModel(
//         id: 'western_009',
//         name: 'كعكة الفانيليا مع الكراميل',
//         description: 'كعكة فانيليا مع طبقة من الكراميل.',
//         price: 24.00,
//         category: 'western_category',
//         imageUrl: 'assets/images/ProductModels/western/vanilla_caramel_cake.jpg',
//       ),
//       // ProductModel(
//       //   id: 'western_010',
//       //   name: 'كعكة الشوكولاتة بالنعناع',
//       //   description: 'كعكة شوكولاتة مع نكهة النعناع المنعشة.',
//       //   price: 26.00,
//       //   category: 'western_category',
//       //   imageUrl: 'assets/images/ProductModels/western/chocolate_mint_cake.jpg',
//       // ),

//       //==========dounts==============//
//       ProductModel(
//         id: 'donut_001',
//         name: 'دوناتس الشوكولاتة',
//         description: 'دوناتس مغطاة بصوص الشوكولاتة الغنية.',
//         price: 3.00,
//         category: 'donuts_category',
//         imageUrl: 'assets/images/ProductModels/donuts/chocolate_donuts.jpg',
//       ),
//       ProductModel(
//         id: 'donut_002',
//         name: 'دوناتس الفانيليا',
//         description: 'دوناتس مغطاة بصوص الفانيليا والسبرينكلز.',
//         price: 3.00,
//         category: 'donuts_category',
//         imageUrl: 'assets/images/ProductModels/donuts/vanilla_donuts.jpg',
//       ),
//       ProductModel(
//         id: 'donut_003',
//         name: 'دوناتس الكراميل المملح',
//         description: 'دوناتس مغطاة بصوص الكراميل المملح.',
//         price: 3.50,
//         category: 'donuts_category',
//         imageUrl: 'assets/images/ProductModels/donuts/salted_caramel_donuts.jpg',
//       ),
//       ProductModel(
//         id: 'donut_004',
//         name: 'دوناتس الفراولة',
//         description: 'دوناتس مغطاة بصوص الفراولة والكريمة.',
//         price: 3.50,
//         category: 'donuts_category',
//         imageUrl: 'assets/images/ProductModels/donuts/strawberry_donuts.jpg',
//       ),
//       ProductModel(
//         id: 'donut_005',
//         name: 'دوناتس الموز',
//         description: 'دوناتس بنكهة الموز مع شوكولاتة.',
//         price: 3.00,
//         category: 'donuts_category',
//         imageUrl: 'assets/images/ProductModels/donuts/banana_donuts.jpg',
//       ),
//       ProductModel(
//         id: 'donut_006',
//         name: 'دوناتس القهوة',
//         description: 'دوناتس بنكهة القهوة مع الموكا.',
//         price: 3.50,
//         category: 'donuts_category',
//         imageUrl: 'assets/images/ProductModels/donuts/coffee_donuts.jpg',
//       ),
//       // ProductModel(
//       //   id: 'donut_007',
//       //   name: 'دوناتس الجبنة',
//       //   description: 'دوناتس محشوة بجبنة الكريمة.',
//       //   price: 4.00,
//       //   category: 'donuts_category',
//       //   imageUrl: 'assets/images/ProductModels/donuts/cheese_donut.jpg',
//       // ),
//       ProductModel(
//         id: 'donut_008',
//         name: 'دوناتس الفستق',
//         description: 'دوناتس مغطاة بالفستق والشوكولاتة.',
//         price: 4.00,
//         category: 'donuts_category',
//         imageUrl: 'assets/images/ProductModels/donuts/pistachio_donuts.jpg',
//       ),
//       ProductModel(
//         id: 'donut_009',
//         name: 'دوناتس اللوتس',
//         description: 'دوناتس مغطاة بصوص اللوتس والكراميل.',
//         price: 3.50,
//         category: 'donuts_category',
//         imageUrl: 'assets/images/ProductModels/donuts/lotus_donuts_with_caramel.jpg',
//       ),
//       ProductModel(
//         id: 'donut_010',
//         name: 'دوناتس الشوكولاتة البيضاء',
//         description: 'دوناتس مغطاة بصوص الشوكولاتة البيضاء.',
//         price: 3.50,
//         category: 'donuts_category',
//         imageUrl: 'assets/images/ProductModels/donuts/white_chocolate_donuts.jpg',
//       ),

//       //==========Biscuits & Cookies==============//

//       ProductModel(
//         id: 'cookie_001',
//         name: 'كوكيز الشوكولاتة',
//         description: 'كوكيز شوكولاتة طرية مع قطع شوكولاتة.',
//         price: 2.00,
//         category: 'cookies_category',
//         imageUrl:
//             'assets/images/ProductModels/cookies/oatmeal_chocolate_chip_cookies.jpg',
//       ),
//       ProductModel(
//         id: 'cookie_002',
//         name: 'كوكيز الزبدة',
//         description: 'كوكيز زبدة كلاسيكية مع سكر.',
//         price: 1.50,
//         category: 'cookies_category',
//         imageUrl: 'assets/images/ProductModels/cookies/butter_cookies.jpg',
//       ),
//       ProductModel(
//         id: 'cookie_003',
//         name: 'كوكيز الفانيليا',
//         description: 'كوكيز فانيليا مع سكر ملون.',
//         price: 1.50,
//         category: 'cookies_category',
//         imageUrl: 'assets/images/ProductModels/cookies/vanilla_sugar_cookies.jpg',
//       ),
//       ProductModel(
//         id: 'cookie_004',
//         name: 'كوكيز الشوكولاتة بالنعناع',
//         description: 'كوكيز شوكولاتة مع نكهة النعناع.',
//         price: 2.00,
//         category: 'cookies_category',
//         imageUrl:
//             'assets/images/ProductModels/cookies/mint_chocolate_chip_cookies.jpg',
//       ),
//       ProductModel(
//         id: 'cookie_005',
//         name: 'كوكيز الجوز',
//         description: 'كوكيز جوز مع القرفة.',
//         price: 2.00,
//         category: 'cookies_category',
//         imageUrl: 'assets/images/ProductModels/cookies/cinnamon_walnut_cookies.jpg',
//       ),
//       ProductModel(
//         id: 'cookie_006',
//         name: 'كوكيز الكراميل المملح',
//         description: 'كوكيز كراميل مع ملح البحر.',
//         price: 2.50,
//         category: 'cookies_category',
//         imageUrl: 'assets/images/ProductModels/cookies/salted_caramel_cookies.jpg',
//       ),
//       ProductModel(
//         id: 'cookie_007',
//         name: 'كوكيز الشوكولاتة البيضاء',
//         description: 'كوكيز شوكولاتة بيضاء مع التوت.',
//         price: 2.00,
//         category: 'cookies_category',
//         imageUrl:
//             'assets/images/ProductModels/cookies/white_chocolate_raspberry_cookies.jpg',
//       ),
//       ProductModel(
//         id: 'cookie_008',
//         name: 'كوكيز اللوز',
//         description: 'كوكيز لوز مع الشوكولاتة.',
//         price: 2.00,
//         category: 'cookies_category',
//         imageUrl: 'assets/images/ProductModels/cookies/chocolate_almond_cookies.jpg',
//       ),
//       ProductModel(
//         id: 'cookie_009',
//         name: 'كوكيز جوز الهند',
//         description: 'كوكيز جوز الهند مع الشوكولاتة.',
//         price: 2.00,
//         category: 'cookies_category',
//         imageUrl:
//             'assets/images/ProductModels/cookies/chocolate_coconut_cookies.jpg',
//       ),
//       ProductModel(
//         id: 'cookie_010',
//         name: 'كوكيز القهوة',
//         description: 'كوكيز قهوة مع الشوكولاتة.',
//         price: 2.50,
//         category: 'cookies_category',
//         imageUrl: 'assets/images/ProductModels/cookies/coffee_chocolate_cookies.jpg',
//       ),
// //==========Healthy Desserts==============//

//       ProductModel(
//         id: 'healthy_001',
//         name: 'كيكة الشوكولاتة الخالية من السكر',
//         description: 'كيكة شوكولاتة خالية من السكر مع ستيفيا.',
//         price: 25.00,
//         category: 'healthy_category',
//         imageUrl:
//             'assets/images/ProductModels/healthy/sugar_free_chocolate_cake.jpg',
//       ),
//       ProductModel(
//         id: 'healthy_002',
//         name: 'كوكيز الشوفان بالعسل',
//         description: 'كوكيز شوفان مع العسل الطبيعي.',
//         price: 2.50,
//         category: 'healthy_category',
//         imageUrl: 'assets/images/ProductModels/healthy/oatmeal_honey_cookies.jpg',
//       ),
//       ProductModel(
//         id: 'healthy_003',
//         name: 'تشيز كيك نباتي',
//         description: 'تشيز كيك نباتي بالتوت الطازج.',
//         price: 30.00,
//         category: 'healthy_category',
//         imageUrl:
//             'assets/images/ProductModels/healthy/vegan_blueberry_cheesecake.jpg',
//       ),
//       ProductModel(
//         id: 'healthy_004',
//         name: 'بارفيه التوت',
//         description: 'بارفيه التوت مع الزبادي اليوناني.',
//         price: 15.00,
//         category: 'healthy_category',
//         imageUrl:
//             'assets/images/ProductModels/healthy/blueberry_parfait_with_greek_yogurt.jpg',
//       ),
//       ProductModel(
//         id: 'healthy_005',
//         name: 'كرات التمر بالمكسرات',
//         description: 'كرات التمر مع المكسرات وجوز الهند.',
//         price: 10.00,
//         category: 'healthy_category',
//         imageUrl: 'assets/images/ProductModels/healthy/date_nut_balls.jpg',
//       ),
//       ProductModel(
//         id: 'healthy_006',
//         name: 'كيكة الجزر الخالية من الجلوتين',
//         description: 'كيكة جزر خالية من الجلوتين.',
//         price: 22.00,
//         category: 'healthy_category',
//         imageUrl: 'assets/images/ProductModels/healthy/gluten_free_carrot_cake.jpg',
//       ),
//       ProductModel(
//         id: 'healthy_007',
//         name: 'كوكيز الشوكولاتة الخالية من الدقيق',
//         description: 'كوكيز شوكولاتة خالية من الدقيق.',
//         price: 2.50,
//         category: 'healthy_category',
//         imageUrl:
//             'assets/images/ProductModels/healthy/flourless_chocolate_cookies.jpg',
//       ),
//       ProductModel(
//         id: 'healthy_008',
//         name: 'بودنغ الشيا',
//         description: 'بودنغ الشيا مع الفواكه الطازجة.',
//         price: 12.00,
//         category: 'healthy_category',
//         imageUrl: 'assets/images/ProductModels/healthy/chia_pudding.jpg',
//       ),
//       ProductModel(
//         id: 'healthy_009',
//         name: 'كعكة الشوفان بالموز',
//         description: 'كعكة شوفان مع الموز والعسل.',
//         price: 18.00,
//         category: 'healthy_category',
//         imageUrl: 'assets/images/ProductModels/healthy/oatmeal_banana_cake.jpg',
//       ),
//       ProductModel(
//         id: 'healthy_010',
//         name: 'كرات البروتين بالشوكولاتة',
//         description: 'كرات بروتين مع الشوكولاتة الداكنة.',
//         price: 3.00,
//         category: 'healthy_category',
//         imageUrl: 'assets/images/ProductModels/healthy/chocolate_protein_balls.jpg',
//       ),
//     ];
//   }

