// File generated by FlutterFire CLI
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase backend.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUUzNqDCtv28u7wWL_sMXTEHkPvvqmZJ0',
    appId: '1:377442339746:web:a280c556b335e4c5fe40fb',
    messagingSenderId: '377442339746',
    projectId: 'cake-and-smile',
    authDomain: 'cake-and-smile.firebaseapp.com',
    storageBucket: 'cake-and-smile.firebasestorage.app',
    measurementId: 'G-QNEHH7MD89',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL1PCxyQiMUa-rd7-TtawFoh1VtE_ZmHg',
    appId: '1:377442339746:android:b61f180878966a3afe40fb',
    messagingSenderId: '377442339746',
    projectId: 'cake-and-smile',
    storageBucket: 'cake-and-smile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXLcNmfbsQa3jAjn3ImtaoZoJ4S7kmjbA',
    appId: '1:377442339746:ios:7277e20fc060cdc6fe40fb',
    messagingSenderId: '377442339746',
    projectId: 'cake-and-smile',
    storageBucket: 'cake-and-smile.firebasestorage.app',
    iosBundleId: 'com.example.cakeAndSmile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    // Add other macOS-specific configurations
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUUzNqDCtv28u7wWL_sMXTEHkPvvqmZJ0',
    appId: '1:377442339746:web:3b2a6d4e684c887cfe40fb',
    messagingSenderId: '377442339746',
    projectId: 'cake-and-smile',
    authDomain: 'cake-and-smile.firebaseapp.com',
    storageBucket: 'cake-and-smile.firebasestorage.app',
    measurementId: 'G-KZ3FT4DQX2',
  );

}